### ISSUE TITLE
Error on load with RTX 4080

### ISSUE THREAD

**Issue by iamlemec** [google/jax#13570]
### Description

Importing `jax` works, and the GPU device is correctly detected by `jax.devices`, but upon doing any array operations (such as `jnp.ones(5)` here) I get the following error:
```
2022-12-08 11:37:51.345475: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2022-12-08 11:37:51.345499: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2022-12-08 11:37:51.352219: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:628] failed to get PTX kernel "broadcast" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2022-12-08 11:37:51.352246: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: INTERNAL: Could not find the corresponding function
```

The last frame of the Python traceback is:
```
File /media/genesis/mlai/jax/jax/interpreters/pxla.py:2136, in ExecuteReplicated.__call__(self, *args)
   2134   out_bufs = self._call_with_tokens(input_bufs)
   2135 else:
-> 2136   out_bufs = self.xla_executable.execute_sharded_on_local_devices(
   2137       input_bufs)
   2138 if dispatch.needs_check_special():
   2139   for bufs in out_bufs:

XlaRuntimeError: INTERNAL: Could not find the corresponding function
```

Which exact PTX kernel is not found depends on the function used, so it seems like a general issue. I also have another computer with identical OS and cuda/jax versions, the only difference being that it has an RTX 2080, and that works fine. Thank you!

### What jax/jaxlib version are you using?

0.3.25+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU (RTX 4080)

### Additional system info

Python 3.10, CUDA Toolkit 11.7.0, cuDNN 8.7.0.84, NVIDIA Driver 525.60.11, nvcc/ptxas 11.7.64

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   33C    P8    21W / 340W |    478MiB / 16376MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2351      G   /usr/bin/gnome-shell               92MiB |
|    0   N/A  N/A      4461      G   /usr/lib64/firefox/firefox        142MiB |
|    0   N/A  N/A     38441      C   /usr/bin/python3.10               238MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jjyyxx** [comment]
Is this related to the recently released CUDA 12? Could current version of Jax work with CUDA 12?

**Comment by ViktorM** [comment]
Also having issues with running Jax on RTX 4090, while there were no problems with 3090 on the same PC and environments in the past. Ubuntu 22.04

**Comment by hawkinsp** [comment]
@iamlemec Can you try updating your CUDA installation to 11.8? Support for the Ada Lovelace family of GPUs was added in CUDA 11.8. https://docs.nvidia.com/cuda/archive/11.8.0/cuda-toolkit-release-notes/index.html#cuda-general-new-features

@jjyyxx JAX doesn't yet support CUDA 12. I'd expect we can support it soon, though.

**Comment by iamlemec** [comment]
Yup, going with CUDA 11.8 did the trick. Thank you @hawkinsp!

**Comment by rafaeltiveron** [comment]
Is there a way more pragmatic? I've installed cuda-11-0, for example. How to make ptxas to summon this cuda version instead of installed version 12?
