### ISSUE TITLE
XlaRuntimeError when jitting certain reductions of large (intermediary) array 

### ISSUE THREAD

**Issue by deasmhumhna** [google/jax#14013]
### Description

Error for `amin`, `amax`, and `logsumexp`:
```
XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to launch CUDA kernel: fusion_4 with block dimensions: 5120x1x1 and grid dimensions: 30733x1x1: CUDA_ERROR_INVALID_VALUE: invalid argument.
```

No errors for `sum`, `mean`, or `prod`.

Minimal reproducing example:
https://colab.research.google.com/drive/1hXANR-lRbHV73SfD5J7FqAwTqLEqsT4P?usp=sharing

The original algorithm uses `sum`/`mean` and runs fine for this size of an array. However, I wanted to see if log-space calculations would result in a lower relative error. 

### What jax/jaxlib version are you using?

jax v0.4.1 jaxlib v0.4.1

### Which accelerator(s) are you using?

GPU

### Additional system info

Google colab

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0    27W /  70W |  13758MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by nouiz** [comment]
@cheshire Can you find someone to look at this XLA issue?

**Comment by cheshire** [comment]
I don't have access to the colab, and is probably not the best way to share the bug.

Is it possible to file an XLA bug and ideally attach input HLO?

**Comment by hawkinsp** [comment]
@deasmhumhna can you open access to the colab, at least?

**Comment by deasmhumhna** [comment]
> @deasmhumhna can you open access to the colab, at least?

It's open now.

**Comment by nouiz** [comment]
I can repro on V100 with the nightly JAX.
A lightly smaller repro:
```
import jax
import jax.numpy as jnp

from functools import partial

@jax.jit
def test(x, reduction=None):
    # jnp.amax, jax.nn.logsumexp also fail
    return jnp.amin(jnp.square(x[:, None, :] - x).sum(axis=-1))
```

The issue is that we try to launch a kernel with 5120 threads per block, but this is limited to 1024:
`fusion with block dimensions: 5120x1x1` Full error:
```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to launch CUDA kernel: fusion with block dimensions: 5120x1x1 and grid dimensions: 30733x1x1: CUDA_ERROR_INVALID_VALUE: invalid argument.
```

Here is an HLO that reproduce the error:
```
HloModule jit_test

region_0.14 {
  Arg_0.15 = f32[] parameter(0)
  Arg_1.16 = f32[] parameter(1)
  ROOT add.17 = f32[] add(Arg_0.15, Arg_1.16)
}

region_1.19 {
  Arg_0.20 = f32[] parameter(0)
  Arg_1.21 = f32[] parameter(1)
  ROOT minimum.22 = f32[] minimum(Arg_0.20, Arg_1.21)
}

ENTRY main.24 {
  Arg_0.1 = f32[50176,3]{1,0} parameter(0), sharding={replicated}
  reshape.4 = f32[50176,1,3]{2,1,0} reshape(Arg_0.1)
  broadcast.6 = f32[50176,1,3]{2,1,0} broadcast(reshape.4), dimensions={0,1,2}
  reshape.7 = f32[50176,3]{1,0} reshape(broadcast.6)
  broadcast.8 = f32[50176,50176,3]{2,1,0} broadcast(reshape.7), dimensions={0,2}
  reshape.5 = f32[1,50176,3]{2,1,0} reshape(Arg_0.1)
  broadcast.9 = f32[1,50176,3]{2,1,0} broadcast(reshape.5), dimensions={0,1,2}
  reshape.10 = f32[50176,3]{1,0} reshape(broadcast.9)
  broadcast.11 = f32[50176,50176,3]{2,1,0} broadcast(reshape.10), dimensions={1,2}
  subtract.12 = f32[50176,50176,3]{2,1,0} subtract(broadcast.8, broadcast.11)
  multiply.13 = f32[50176,50176,3]{2,1,0} multiply(subtract.12, subtract.12)
  constant.3 = f32[] constant(0)
  reduce.18 = f32[50176,50176]{1,0} reduce(multiply.13, constant.3), dimensions={2}, to_apply=region_0.14
  constant.2 = f32[] constant(inf)
  ROOT reduce.23 = f32[] reduce(reduce.18, constant.2), dimensions={0,1}, to_apply=region_1.19
}
```

**Comment by cheshire** [comment]
Tracked internally as P1 in b/268425676

**Comment by thomasjoerg** [comment]
Thanks for the convenient reproducer, Frédéric.

I found the culprit and have a fix in-flight.

**Comment by nouiz** [comment]
If I use upstream TF and upstream JAX, I have this output:
```
<function amin at 0x7f5efb0b4d30> None
<function amax at 0x7f5efb0b4940> None
<function logsumexp at 0x7f5efac68430> None
<function sum at 0x7f5efb0b4160> None
<function mean at 0x7f5efb0ba670> None
<function prod at 0x7f5efb0b4550> None
```
So it is fixed upstream.
Thanks for the report and the nice notebook.
