### ISSUE TITLE
Possible reasons for GPU not being found? 

### ISSUE THREAD

**Issue by ljmartin** [google/jax#1418]
Hi all, and thanks for your work on JAX.
I seem to have installed via the pip wheel without any problems, but any operations requiring the GPU cause the 'GPU not found' warning. Wondering if anyone has any methods to help me figure out why? Below shows the places Ive looked for an error. Any comment is appreciated :) thanks

Running Ubuntu 18.04 with a working CUDA10.0 installation, only new thing was "installing" CUDNN. 

cuda version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

CUDNN check:
`cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2`
```
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

Install script:
```
# install jaxlib
PYTHON_VERSION=cp37  # alternatives: cp27, cp35, cp36, cp37
CUDA_VERSION=cuda100  # alternatives: cuda90, cuda92, cuda100, cuda101
PLATFORM=linux_x86_64  # alternatives: linux_x86_64
BASE_URL='https://storage.googleapis.com/jax-releases'
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.29-$PYTHON_VERSION-none-$PLATFORM.whl

pip install --upgrade jax  # install jax(base)
```

Install log (not sure about that previous installation - I had run `pip uninstall jax` and confirmed jax wouldn't import before this install:
```
Collecting jaxlib==0.1.29 from https://storage.googleapis.com/jax-releases/cuda100/jaxlib-0.1.29-cp37-none-linux_x86_64.whl
  Using cached https://storage.googleapis.com/jax-releases/cuda100/jaxlib-0.1.29-cp37-none-linux_x86_64.whl
Requirement already satisfied, skipping upgrade: six in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jaxlib==0.1.29) (1.12.0)
Requirement already satisfied, skipping upgrade: numpy>=1.12 in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jaxlib==0.1.29) (1.16.4)
Requirement already satisfied, skipping upgrade: scipy in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jaxlib==0.1.29) (1.3.0)
Requirement already satisfied, skipping upgrade: absl-py in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jaxlib==0.1.29) (0.8.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.0 in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jaxlib==0.1.29) (3.9.2)
Requirement already satisfied, skipping upgrade: setuptools in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from protobuf>=3.6.0->jaxlib==0.1.29) (41.0.1)
Installing collected packages: jaxlib
  Found existing installation: jaxlib 0.1.29
    Uninstalling jaxlib-0.1.29:
      Successfully uninstalled jaxlib-0.1.29
Successfully installed jaxlib-0.1.29
Collecting jax
Requirement already satisfied, skipping upgrade: fastcache in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (1.1.0)
Requirement already satisfied, skipping upgrade: six in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (1.12.0)
Requirement already satisfied, skipping upgrade: numpy>=1.12 in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (1.16.4)
Requirement already satisfied, skipping upgrade: absl-py in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (0.8.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.0 in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (3.9.2)
Requirement already satisfied, skipping upgrade: opt-einsum in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from jax) (3.1.0)
Requirement already satisfied, skipping upgrade: setuptools in /home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages (from protobuf>=3.6.0->jax) (41.0.1)
Installing collected packages: jax
Successfully installed jax-0.1.46
```

GPU warning:
```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> from jax import random
>>> key = random.PRNGKey(0)
2019-10-01 10:40:06.399412: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:334] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
/home/lewis/miniconda3/envs/lew_conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py:115: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
```

edit: with relation to https://github.com/google/jax/issues/1377 , I already have `export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH"` in my bashrc

**Comment by ljmartin** [comment]
So I discovered somewhere along the way Ive broken CUDA, since nvidia-smi fails due to driver reasons.... Closing and Ill come back if it persists...

**Comment by ljmartin** [comment]
Can confirm it works fine after reinstalling CUDA driver.

**Comment by Nerkan78** [comment]
My nvidia-smi works fine but this issue still occurs? What other reasons can be?

**Comment by skye** [comment]
@Nerkan78 can you open a new issue describing your setup (e.g. cuda version + how you're installing jaxlib) and the exact failure you're seeing? Thanks!
