### ISSUE TITLE
jnp.isfinite bug

### ISSUE THREAD

**Issue by fredguth** [google/jax#14721]
### Description

`jnp.isfinite` triggers cuda error.

```python
import jax.numpy as jnp

jnp.isfinite(jnp.array([1,2]))

```
error:
````
2023-02-28 17:05:29.820789: E external[/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429](https://vscode-remote+ssh-002dremote-002b192-002e168-002e68-002e103.vscode-resource.vscode-cdn.net/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429)] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-02-28 17:05:29.822036: E external[/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57](https://vscode-remote+ssh-002dremote-002b192-002e168-002e68-002e103.vscode-resource.vscode-cdn.net/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57)] INTERNAL: RET_CHECK failure (external[/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:626](https://vscode-remote+ssh-002dremote-002b192-002e168-002e68-002e103.vscode-resource.vscode-cdn.net/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:626)) dnn != nullptr 
*** Begin stack trace ***
	_PyObject_MakeTpCall	
	_PyEval_EvalFrameDefault
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	...
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalFrameDefault
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	Py_RunMain
	Py_BytesMain
	
	__libc_start_main
*** End stack trace ***
```

### What jax/jaxlib version are you using?

jax v.0.4.3., jaxlib v.0.4.3+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.15

### NVIDIA GPU info

````
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   38C    P8     9W / 250W |  11146MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    350485      C   ...a3/envs/jaxai2/bin/python    10692MiB |
|    0   N/A  N/A    354089      C   ...a3/envs/jaxai2/bin/python      450MiB |
+-----------------------------------------------------------------------------+

````

**Comment by hawkinsp** [comment]
I think actually that's a symptom of you running out of GPU memory.

You appear to be running two JAX processes on the same GPU. See also https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

The error message could be improved, certainly.

**Comment by fredguth** [comment]
I am using on Jupyter/VSCode/Remote. 
I have two notebooks with the same code and using the same environment. 
I added `%env XLA_PYTHON_CLIENT_MEM_FRACTION=0.2` in the first cell.
I kill all processes and check `nvidia-smi`: 100% of memory available.
I run in one of the notebooks and it works.  
I kill all processes and check `nvidia-smi`: 100% of memory available.
I run in  the other notebook and it fails.  (I even tried to copy the file that works but ... no, it is does not work).
I also tried cloning the environment and updating jax in one of them and the same error happens with jax 0.4.4
I am monitoring my GPU memory usage and it is never over 40%.  I believe you are right that there is a memory leak somewhere and maybe it is not jax related, but I have no idea on how to debug.

¯\_(ツ)_/¯. 

BTW, in the notebook where it fails, if I use numpy (which I guess moves the computation to the cpu), it works.
`np.isfinite(jnp.array([1.,2]))` works.
