### ISSUE TITLE
Could not load library libcublasLt.so.12. Error

### ISSUE THREAD

**Issue by MandMarc** [google/jax#14931]
### Description

I have some issues with a new jax install. While installation concludes without error, as soon as I try to do operations with an array I get the following message:
```
>>> import jax.numpy as jnp
>>> a = jnp.arange(4)
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

This looks a lot like a faulty cuda install, however, inside another virtual environment I'm running an older jax installation without any error (jax=0.3.25, jaxlib=0.3.25+cuda11+cudnn82).

I've tried jax=0.4.6, jaxlib=0.4.6+cuda11.cudnn82 as well as the corresponding version with cudnn86 giving the same error.

It seems like jax is looking for something cuda12 related?

### What jax/jaxlib version are you using?

jax=0.4.6, jaxlib=0.4.6+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux (Ubuntu)

### NVIDIA GPU info
On my system I installed cuda 11.8 and cudnn 8.8.
nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```
nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:0C:00.0  On |                  N/A |
|  0%   53C    P5    47W / 340W |   9157MiB / 10240MiB |     37%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by meereeum** [comment]
same issue! jax seems to be expecting CUDA 12 even though the build is ostensibly for 11

**Comment by jakevdp** [comment]
JAX is not yet compatible with CUDA 12. THe `nvidia-smi` output above indicates that you have CUDA 12 installed on your system. I'd suggest downgrading CUDA to 11.X for now; the next jaxlib release should hopefully include pre-built CUDA 12 wheels.

**Comment by meereeum** [comment]
I was able to resolve this only by downgrading:
```
$ pip install jax==0.4.2 https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.2+cuda11.cudnn86-cp310-cp310-manylinux2014_x86_64.whl
```

maybe I'm missing something; I'm not sure why `$ nvidia smi` shows CUDA 12 (it does for me too) whereas
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```
also, all the library files that I see are for CUDA 11, e.g.
```
$ find /usr/local -name 'libcublasLt.so.*'
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcublasLt.so.11
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcublasLt.so.11.9.2.110
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcublasLt.so.11.11.3.6
```

**Comment by meereeum** [comment]
@jakevdp I do believe the problem is on jax's end (as of ~0.4.3)

**Comment by jakevdp** [comment]
Did you make sure to install the jaxlib that matches your CUDA version? https://github.com/google/jax#pip-installation-gpu-cuda

**Comment by meereeum** [comment]
yep, CUDA 11.6 (and cuDNN 8.8)

just to reiterate the difference between builds:
```
$ pip install jax==$VS https://storage.googleapis.com/jax-releases/cuda11/jaxlib-${VS}+cuda11.cudnn86-cp310-cp310-manylinux2014_x86_64.whl
```
- `VS=0.4.3` (or latest) => crashes on GPU computation ("Could not load library libcublasLt.so.12")
- `VS=0.4.2` => works fine

**Comment by meereeum** [comment]
> Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

^^ jax is looking for a file that presumably would exist if CUDA 12 were installed. but it's not — I have CUDA 11 / `libcublasLt.so.11` — so the file can't be loaded. this is unexpected behavior for a jaxlib build that, in name, is for CUDA 11

**Comment by yashk2810** [comment]
> $ nvidia-smi shows CUDA 12 (it does for me too)

nvidia-smi shows the version your driver is capable of handling not the actual version installed in your machine.

**Comment by hawkinsp** [comment]
Can you please confirm which version of cudnn you have installed? For example you have  cudnn installed by Ubuntu or Debian packages, show the output of `dpkg -l libcudnn`?

I think this means you have the CUDA 12 version of cudnn installed. You *must* have the CUDA 11 version installed. For example if using NVIDIA's Ubuntu packages, you must have `8.8.1.3-1+cuda11.8` not `8.8.1.3-1+cuda12.0` installed.

**Comment by MandMarc** [comment]
I did not install cudnn with any package manager. I manually unpacked the files into the target libraries after downloading them from nvidia, so I cannot check the version as you suggested. However, I set up my system by the end of last year and I'm pretty sure there was no cudnn released for cuda12 back then. So, I'm positive I'm dealing with the cuda11.8 version. If there is another way to check and make sure please let me know.
As others have pointed out, nvidia-smi doesn't show what cuda version you use, but nvcc --version does (which is why I included it). My other jax 3.25 version is still running and works on the same system with cuda11.8, I suppose this would not be the case if I were using libcudnn8.8.1.3-1+cuda12.0 with cuda11.8.

**Comment by hawkinsp** [comment]
The only thing that is relevant here is the version of cudnn you are using, not nvcc and not nvidia-smi.

I would check (e.g., using `find` or `locate`) the set of files named `libcudnn*` on your machine.

**Comment by MandMarc** [comment]
Alright, thanks for the suggestion, this (indirectly) solved it! Using $ find /usr -iname "*libcudnn*" did not return any results (?) for some reason. I simply installed libcudnn via (see nvidia website), using the package manager this time
```
sudo apt-get install libcudnn8=8.8.1.3-1+cuda11.8
sudo apt-get install libcudnn8-dev=8.8.1.3-1+cuda11.8
```
After restarting and reinstalling jax 4.6 (pip install "jax[cuda11_cudnn86]" ) everything works. I am still confused about why there were apparently no libcudnn files because inside another venv, the older jax version was (and still is) functional. Either way, the issues is now solved for me. Maybe double checking the libcudnn files also solves meereeum's issue too?

**Comment by meereeum** [comment]
Aha, @hawkinsp you are correct. I'm working on a shared machine (no sudo) but I do see:
```
$ apt list --installed | grep cudnn

libcudnn8-dev/unknown,now 8.8.0.121-1+cuda12.0 amd64 [installed,upgradable to: 8.8.1.3-1+cuda12.0]
libcudnn8/unknown,now 8.8.0.121-1+cuda12.0 amd64 [installed,upgradable to: 8.8.1.3-1+cuda12.0]
```

Odd that this only becomes an issue in recent jax versions. I'll ping the admin to update the package. thank you!

**Comment by meereeum** [comment]
by the way, I think the files associated with the package are named `cudnn` (not `libcudnn`) – which is why @MandMarc didn't find anything

**Comment by hawkinsp** [comment]
I think we solved this above; closing.

If anyone is still struggling with this issue, we added support for `pip`-installed CUDA and CUDNN in jax 0.4.7, which is much easier to manage. See: https://github.com/google/jax/pull/15278

**Comment by arrrrr3186** [comment]
Hello @meereeum , 
In continuation of the above conversation, 
can below command in the specific env, rather in the whole system
$ pip install jax==0.4.2 https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.2+cuda11.cudnn86-cp310-cp310-manylinux2014_x86_64.whl
