### ISSUE TITLE
JAX 0.4.8 on CUDA 12.0, H100, Driver: 525.60.13  yields CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by S-Roecken** [google/jax#15752]
### Description

Hi there, 

On H100 GPU with CUDA 12.0, Nvidia-Driver 525.60.13 Jax seems to have some issues. First a sample to reproduce and below that the error message:

`import jax.numpy as jnp

a = jnp.array([[1,2,3], [4,5,6], [1,2,3]])
b = jnp.array([[1,2,3], [4,5,6], [1,2,3]])

result = jnp.matmul(a, b)
print("Result: ", result)`

2023-04-26 07:08:38.181946: W external/xla/xla/stream_executor/cuda/cuda_dnn.cc:397] There was an error before creating cudnn handle: cudaGetErrorName symbol not found. : cudaGetErrorString symbol not found.
2023-04-26 07:08:38.182026: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "bug_report_script.py", line 7, in <module>
    result = jnp.matmul(a, b)
.....
.....
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

As an additional note, I observed a similar error on the A100, but then it was due to the GPU being memory-wise occupied. In this case the GPU is completely free.

Thank you in advance.

Best
Sebastien

### What jax/jaxlib version are you using?

jax 0.4.8, jaxlib 0.4.7+cuda12.cudnn88

### Which accelerator(s) are you using?

GPU H100

### Additional system info

Ubuntu 22.04 LTS

**Comment by yhtang** [comment]
Hi Sebastien! Is this on a cloud platform or your local setup?

**Comment by S-Roecken** [comment]
Hi,

Thank you for your reply! A vendor setup the H100 server and we accessing it via ssh for testing purposes.

**Comment by yhtang** [comment]
When I run the example as given in the OP on H100, JAX simply hangs indefinitely.

**Comment by yhtang** [comment]
Will look into that further.

**Comment by yhtang** [comment]
The example works with CUDA 12.1:
```
# nvidia-smi
Sat Apr 29 02:04:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA H100 PCIe    On   | 00000000:C1:00.0 Off |                    0 |
| N/A   30C    P0    45W / 310W |      0MiB / 81559MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

# python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax.numpy as jnp
>>> a = jnp.array([[1,2,3], [4,5,6], [1,2,3]])
>>> b = jnp.array([[1,2,3], [4,5,6], [1,2,3]])
>>> result = jnp.matmul(a, b)
>>> print("Result: ", result)
Result:  [[12 18 24]
 [30 45 60]
 [12 18 24]]
```

**Comment by hawkinsp** [comment]
Is this still an issue? Given yhtang@'s comments, I suspect everything is fine now.

Support for H100 has also matured significantly since April.

**Comment by hawkinsp** [comment]
There was no update since November, and we routinely run on H100, so I think this problem was fixed by either a newer CUDA or a newer JAX.
