### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by kbali1297** [google/jax#15774]
### Description

I installed the latest cuda packages and jax 0.4.8. 

```
import jax.numpy as np

t = np.ones(5)
```

When I start to use it to create a simple array as above, the following error below shows up. I've repeatedly uninstalled and re-installed cuda and jax packages.  

```
2023-04-27 18:06:04.839079: E external[/xla/xla/stream_executor/cuda/cuda_dnn.cc:429](https://file+.vscode-resource.vscode-cdn.net/xla/xla/stream_executor/cuda/cuda_dnn.cc:429)] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
[/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/08_Cylinderflow.ipynb](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/08_Cylinderflow.ipynb) Cell 4 in ()
      [1](vscode-notebook-cell:/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/08_Cylinderflow.ipynb#X12sZmlsZQ%3D%3D?line=0) import jax.numpy as np
----> [3](vscode-notebook-cell:/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/08_Cylinderflow.ipynb#X12sZmlsZQ%3D%3D?line=2) t = np.ones(5)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py:2092](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py:2092), in ones(shape, dtype)
   2090 shape = canonicalize_shape(shape)
   2091 dtypes.check_user_dtype_supported(dtype, "ones")
-> 2092 return lax.full(shape, 1, _jnp_dtype(dtype))

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:1190](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:1190), in full(shape, fill_value, dtype)
   1188 dtype = dtypes.canonicalize_dtype(dtype or _dtype(fill_value))
   1189 fill_value = _convert_element_type(fill_value, dtype, weak_type)
-> 1190 return broadcast(fill_value, shape)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:756](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:756), in broadcast(operand, sizes)
    742 """Broadcasts an array, adding new leading dimensions
    743 
    744 Args:
   (...)
    753   jax.lax.broadcast_in_dim : add new dimensions at any location in the array shape.
    754 """
    755 dims = tuple(range(len(sizes), len(sizes) + np.ndim(operand)))
--> 756 return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:784](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/lax/lax.py:784), in broadcast_in_dim(operand, shape, broadcast_dimensions)
    782 else:
    783   dyn_shape, static_shape = [], shape  # type: ignore
--> 784 return broadcast_in_dim_p.bind(
    785     operand, *dyn_shape, shape=tuple(static_shape),
    786     broadcast_dimensions=tuple(broadcast_dimensions))

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:360](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:360), in Primitive.bind(self, *args, **params)
    357 def bind(self, *args, **params):
    358   assert (not config.jax_enable_checks or
    359           all(isinstance(arg, Tracer) or valid_jaxtype(arg) for arg in args)), args
--> 360   return self.bind_with_trace(find_top_trace(args), args, params)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:363](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:363), in Primitive.bind_with_trace(self, trace, args, params)
    362 def bind_with_trace(self, trace, args, params):
--> 363   out = trace.process_primitive(self, map(trace.full_raise, args), params)
    364   return map(full_lower, out) if self.multiple_results else full_lower(out)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:817](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/core.py:817), in EvalTrace.process_primitive(self, primitive, tracers, params)
    816 def process_primitive(self, primitive, tracers, params):
--> 817   return primitive.impl(*tracers, **params)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:117](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:117), in apply_primitive(prim, *args, **params)
    114 from jax._src import pjit
    116 try:
--> 117   compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
    118                                         **params)
    119 except pxla.DeviceAssignmentMismatchError as e:
    120   fails, = e.args

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/util.py:253](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/util.py:253), in cache..wrap..wrapper(*args, **kwargs)
    251   return f(*args, **kwargs)
    252 else:
--> 253   return cached(config._trace_context(), *args, **kwargs)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/util.py:246](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/util.py:246), in cache..wrap..cached(_, *args, **kwargs)
    244 @functools.lru_cache(max_size)
    245 def cached(_, *args, **kwargs):
--> 246   return f(*args, **kwargs)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:208](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:208), in xla_primitive_callable(prim, *arg_specs, **params)
    206   else:
    207     return out,
--> 208 compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), prim.name,
    209                                   donated_invars, False, *arg_specs)
    210 if not prim.multiple_results:
    211   return lambda *args, **kw: compiled(*args, **kw)[0]

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:254](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:254), in _xla_callable_uncached(fun, name, donated_invars, keep_unused, *arg_specs)
    251 computation = sharded_lowering(fun, name, donated_invars, keep_unused,
    252                                *arg_specs, lowering_platform=None)
    253 allow_prop = [True] * len(computation.compile_args['global_out_avals'])
--> 254 return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py:2816](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py:2816), in MeshComputation.compile(self, _allow_propagation_to_outputs, _allow_compile_replicated)
   2813     self._executable = MeshExecutable.from_trivial_jaxpr(
   2814         **self.compile_args)
   2815   else:
-> 2816     self._executable = UnloadedMeshExecutable.from_hlo(
   2817         self._name,
   2818         self._hlo,
   2819         **self.compile_args,
   2820         _allow_propagation_to_outputs=_allow_propagation_to_outputs,
   2821         _allow_compile_replicated=_allow_compile_replicated)
   2822 return self._executable

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py:3028](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py:3028), in UnloadedMeshExecutable.from_hlo(name, computation, mesh, global_in_avals, global_out_avals, in_shardings, out_shardings, spmd_lowering, tuple_args, auto_spmd_lowering, _allow_propagation_to_outputs, _allow_compile_replicated, unordered_effects, ordered_effects, host_callbacks, keepalive, kept_var_idx, backend, device_assignment, committed, pmap_nreps)
   3024 else:
   3025   with dispatch.log_elapsed_time(f"Finished XLA compilation of {name} "
   3026                                  "in {elapsed_time} sec",
   3027                                  event=dispatch.BACKEND_COMPILE_EVENT):
-> 3028     xla_executable = dispatch.compile_or_get_cached(
   3029         backend, computation, compile_options, host_callbacks)
   3031   if auto_spmd_lowering:
   3032     assert mesh is not None

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:526](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:526), in compile_or_get_cached(backend, computation, compile_options, host_callbacks)
    522     _cache_write(serialized_computation, compile_time, module_name,
    523                  compile_options, backend, compiled, host_callbacks)
    524     return compiled
--> 526 return backend_compile(backend, serialized_computation, compile_options,
    527                        host_callbacks)

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/profiler.py:314](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/profiler.py:314), in annotate_function..wrapper(*args, **kwargs)
    311 @wraps(func)
    312 def wrapper(*args, **kwargs):
    313   with TraceAnnotation(name, **decorator_kwargs):
--> 314     return func(*args, **kwargs)
    315   return wrapper

File [~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:471](https://file+.vscode-resource.vscode-cdn.net/home/kartik/Desktop/JAXFLUIDS/notebooks/08_Cylinderflow/~/anaconda3/lib/python3.9/site-packages/jax/_src/dispatch.py:471), in backend_compile(backend, built_c, options, host_callbacks)
    466   return backend.compile(built_c, compile_options=options,
    467                          host_callbacks=host_callbacks)
    468 # Some backends don't have `host_callbacks` option yet
    469 # TODO(sharadmv): remove this fallback when all backends allow `compile`
    470 # to take in `host_callbacks`
--> 471 return backend.compile(built_c, compile_options=options)

XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

The error message doesn't illustrate where exactly the bug is at all. 
It would be great to know solutions to this problem asap :(

Thanks!

### What jax/jaxlib version are you using?

jax: 0.4.8 
jaxlib : 0.4.7+cuda12.cudnn88

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 20.04

### NVIDIA GPU info
![Screenshot from 2023-04-27 18-44-04](https://user-images.githubusercontent.com/102038814/234932565-2b9939c8-ac7f-49ec-b659-ca48df065e63.png)

GTX 1650

**Comment by kbali1297** [comment]
Hey everyone! Jax is now working with GPU support for me now. The mistake I was doing was that I didn't install cuDNN 8.9 after CUDA toolkit 12.1. Now that these dependencies are satisfied I'm currently having no problems with the code anymore.

Really sorry for not researching enough before raising the issue but I hope this will benefit those in the same boat!
