### ISSUE TITLE
JAX cannot create cudnn handle (CUDNN_STATUS_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by limesqueezy** [google/jax#16078]
### Description

I have managed to solve the following problem by simply [installing `cudnn`](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-deb). Please let me know if I have to change the label from `bug` to `discussion` or something similar :)

I will still post it since in the [Installation tutorial](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier) it was not mentioned that `cudnn` had to be installed. Someone can easily assume that, like pytorch, we would not need `cudnn`. As a matter of fact, according to the instructions I feel like I should not have installed `cudnn` since it's installed from pip wheels.

Reproducing this is quite easy since I could not even get simple commands to run. The GPU, Quadro M1000M, is quite old (Maxwell arch). Running `print(jax.lib.xla_bridge.get_backend().platform)` works. I also went through the [memory allocation](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) route setting `XLA_PYTHON_CLIENT_PREALLOCATE=false` but still no hope :( 

`jax.numpy.ones((3,))` returns,

```
2023-05-20 20:06:28.373077: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-05-20 20:06:28.373132: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 697237504 bytes free, 4231397376 bytes total.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 2122, in ones
    return lax.full(shape, 1, _jnp_dtype(dtype))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 1203, in full
    return broadcast(fill_value, shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 768, in broadcast
    return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 796, in broadcast_in_dim
    return broadcast_in_dim_p.bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 131, in apply_primitive
    compiled_fun = xla_primitive_callable(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/util.py", line 284, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/util.py", line 277, in cached
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 222, in xla_primitive_callable
    compiled = _xla_callable_uncached(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 252, in _xla_callable_uncached
    return computation.compile().unsafe_call
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

`jax.random.PRNGKey(0)` returns,

```
2023-05-20 20:08:18.894443: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-05-20 20:08:18.894540: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 707198976 bytes free, 4231397376 bytes total.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 734, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 746, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 751, in random_seed_impl_base
    return seed(seeds)
           ^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 980, in threefry_seed
    return _threefry_seed(seed)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/pjit.py", line 208, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/pjit.py", line 1088, in _pjit_call_impl
    always_lower=False, lowering_platform=None).compile()
                                                ^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 734, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 746, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 751, in random_seed_impl_base
    return seed(seeds)
           ^^^^^^^^^^^
  File "/home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages/jax/_src/prng.py", line 980, in threefry_seed
    return _threefry_seed(seed)
           ^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

### What jax/jaxlib version are you using?

jax: 0.4.10, jaxlib: 0.4.10+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.11.3, Debian 11, 5.10.0-23-amd64

### NVIDIA GPU info

```
Sat May 20 19:59:01 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M1000M       On   | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P0    N/A /  N/A |    334MiB /  4035MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2746      G   /usr/lib/xorg/Xorg                 82MiB |
|    0   N/A  N/A      2946      G   /usr/bin/gnome-shell               53MiB |
|    0   N/A  N/A      4368      G   ...b/firefox-esr/firefox-esr      154MiB |
|    0   N/A  N/A     23863      G   ...RendererForSitePerProcess       37MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Hi - from your link I'm assuming you were referring to the installation instructions that recommend this:
```
pip install --upgrade "jax[cuda12_pip]"
```
If so, then the CUDNN dependency is explicitly declared as part of this installation: https://github.com/google/jax/blob/2f215e5eabddd0260756d748d1f7e67f877ce921/setup.py#L109-L119

If you ran this line and did *not* get a viable cudnn installation on your system, it would be good for us to understand why. Do you have the log of your original `pip install` command?

**Comment by limesqueezy** [comment]
Unfortunately I don't, since my terminal does not save the output but I'm positive on having run the following command since the input is saved,

`pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

After that I could import the library but got the errors mentioned above. I will try to remove  `cudnn` to give you more information. Apart from the output of `pip install` would there be anything else that would let us probe the innards of the installation?

**Comment by limesqueezy** [comment]
Removing the locally installed `cudnn` gave rise to the actual issue here but broke the harmony between torch and jax on my system.

I'm on a conda environment and had `jax` installed before `torch`, the issue I install the versions that use preshipped nvidia libraries. In this order, at this time, using `cuda11.2` and without any thoughtful reasoning `jax` will first install its own `cudnn` and `torch` would overwrite it. Typical python versioning. The most torturous part is that running `pip show nvidia-cudnn-cu11` returns,

```
Name: nvidia-cudnn-cu11
Version: 8.9.1.23
Summary: cuDNN runtime libraries
Home-page: https://developer.nvidia.com/cuda-zone
Author: Nvidia CUDA Installer Team
Author-email: cuda_installer@nvidia.com
License: NVIDIA Proprietary Software
Location: /home/lemon/miniconda3/envs/nn/lib/python3.11/site-packages
Requires: nvidia-cublas-cu11
Required-by: 
```

> Yes, `pip` is environment-wide installed `/home/lemon/miniconda3/envs/nn/bin/pip`

So I would assume that `nvidia-cudnn-cu11>=8.6` which apparently is not the case since `torch.backends.cudnn.version()` returns `8500` now that I have uninstalled the local `cudnn`.

I then proceeded to force re-install 
```
pip install --force-reinstall "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
But still `torch.backends.cudnn.version()` returns `8500`

So I tried the two combinations listed below, first install `jax` then `torch` and then in reverse order, none of them worked. I am attaching the exact commands I run and their respective errors,

conda env create -n dev
conda activate dev
conda install pip
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install torch torchvision
python
> import torch
> import jax
> print(jax.lib.xla_bridge.get_backend().platform)
gpu
> torch.backends.cudnn.version()
8500
> a = jax.numpy.arange((6), dtype=jax.numpy.float32)
2023-05-24 00:09:07.395059: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:427] Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
[...]

Trying to `pip install --force-reinstall "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` will lead to the same configuration described below i.e. Torch->JAX

---

conda env create -n dev0
conda activate dev0
conda install pip
pip install torch torchvision
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
python
> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lemon/miniconda3/envs/dev/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory
> import jax
> print(jax.lib.xla_bridge.get_backend().platform)
gpu
> a = jax.numpy.arange((6), dtype=jax.numpy.float32)

JAX works Torch doesn't, which makes sense according to the infuriating `nvidia-cudnn-cu11==8.5.0.96` dependency of torch.

The issue persist and I almost feel embarrassed for having used `colab` for so long and cannot make this simple thing work locally. My last resort is to upgrade `cuda` but even that could be avoided since PyTorch only needs nvidia drivers.

**Comment by 1e100** [comment]
Same here. I have tried both the "local" and "pip" install. I'm unable to use Jax. And I can't upgrade to CUDA 12 because most of my work is in PyTorch, which is not yet compatible with 12.

**Comment by 1e100** [comment]
Tried everything: DEB or TAR install of cudnn, local install of CUDA from DEB or TAR, network install of CUDA - nothing works. From which I conclude that Jax probably doesn't work at all with CUDA 11.8 on Ubuntu 22.04, or if it does, then it maybe needs some LD_LIBRARY_PATH or something like that.

**Comment by 1e100** [comment]
And finally, tried to build from source - still the same error. Pretty sure it's not CUDA or cuDNN - PyTorch works fine on the same machine.

**Comment by 1e100** [comment]
FYI: in my case this ended up being caused by the use of TF Data. Once I disallowed the use of GPU to TF, I was able to run my program. OP probably has the same issue. This error message needs to be more specific as to the cause of the failure. Currently it's not even clear from the error message that insufficient VRAM or something else is the problem. Also, in my case, immediately after CUDNN failure there's another message that suggests that GPU driver might be too old (which it isn't).

**Comment by ecolss** [comment]
> And finally, tried to build from source - still the same error. Pretty sure it's not CUDA or cuDNN - PyTorch works fine on the same machine.

This is so sad, I tried many googled solutions as well and still cannot get Jax working on my machine, and this is my first time using Jax, and am pretty sure won't be a Jax user (stick with pytorch), it's just because some Google paper used Jax and I wanted to play with that code, so I had to use Jax...

**Comment by 1e100** [comment]
@ecolss - note that I did get it to work by disabling GPUs for TensorFlow, which you might also be using transitively without realizing it, through `tf.data`. Once this was resolved, I did not encounter any further issues.

**Comment by ecolss** [comment]
@1e100 glad you worked it out, but still strange to me why we need to disable some modules in order to use Jax, which already sounds like an inconvenient hack to users

**Comment by 1e100** [comment]
@ecolss - I'd also prefer a native (or at least TF-free) data loading solution, but in its absence `tf.data` (which is what's causing the issue here) is unavoidable, unfortunately. You could also use PyTorch's `DataLoader` class which doesn't have this issue, or install `tensorflow-cpu` which would not try to grab your GPU when it starts. 

I think some of these issues come from not understanding where Jax sits in terms of abstraction hierarchy. Jax itself is basically a set of primitives to build higher level libraries. Some have already been built (Orbax, Optax, Flax, etc), and some are yet to be built. I'd love to have a Jax-native data loader that doesn't depend on anything else. Until that happens though, these are the workarounds.

**Comment by jakevdp** [comment]
I think the original issue has been resolved. Thanks!
