### ISSUE TITLE
jax only recognized 1 out of 8 gpus

### ISSUE THREAD

**Issue by wbrenton** [google/jax#16438]
### Description

I'm trying to use jax with 8 nvidia a100 GPUs and jax.devices only recognizes 1 of them. In a fresh virtual environment I have executed the following command. 

As you can see there are 8 A100 running CUDA Version: 12.0 
```(jax_env) willb@ip-26-0-130-134:~$ nvidia-smi
Thu Jun 15 18:53:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:10:1C.0 Off |                    0 |
| N/A   36C    P0    55W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:10:1D.0 Off |                    0 |
| N/A   34C    P0    54W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:20:1C.0 Off |                    0 |
| N/A   36C    P0    57W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:20:1D.0 Off |                    0 |
| N/A   35C    P0    56W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:90:1C.0 Off |                    0 |
| N/A   35C    P0    55W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:90:1D.0 Off |                    0 |
| N/A   34C    P0    56W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:A0:1C.0 Off |                    0 |
| N/A   35C    P0    52W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:A0:1D.0 Off |                    0 |
| N/A   36C    P0    61W / 400W |      3MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
pip is upgraded
```
(jax_env) willb@ip-26-0-130-134:~$ pip install --upgrade pip
Requirement already satisfied: pip in ./jax_env/lib/python3.8/site-packages (23.1.2)
```
installing jax[cuda] following https://github.com/google/jax#installation
```
(jax_env) willb@ip-26-0-130-134:~$ pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Requirement already satisfied: jax[cuda12_pip] in ./jax_env/lib/python3.8/site-packages (0.4.8)
Collecting jax[cuda12_pip]
  Using cached jax-0.4.12-py3-none-any.whl
Requirement already satisfied: ml-dtypes>=0.1.0 in ./jax_env/lib/python3.8/site-packages (from jax[cuda12_pip]) (0.2.0)
Requirement already satisfied: numpy>=1.21 in ./jax_env/lib/python3.8/site-packages (from jax[cuda12_pip]) (1.24.3)
Requirement already satisfied: opt-einsum in ./jax_env/lib/python3.8/site-packages (from jax[cuda12_pip]) (3.3.0)
Requirement already satisfied: scipy>=1.7 in ./jax_env/lib/python3.8/site-packages (from jax[cuda12_pip]) (1.10.1)
Requirement already satisfied: importlib-metadata>=4.6 in ./jax_env/lib/python3.8/site-packages (from jax[cuda12_pip]) (6.6.0)
INFO: pip is looking at multiple versions of jax[cuda12-pip] to determine which version is compatible with other requirements. This could take a while.
  Using cached jax-0.4.11-py3-none-any.whl
Collecting jaxlib==0.4.11+cuda12.cudnn88 (from jax[cuda12_pip])
  Using cached https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.11%2Bcuda12.cudnn88-cp38-cp38-manylinux2014_x86_64.whl (170.8 MB)
Collecting nvidia-cublas-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 6.1 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 44.5 MB/s eta 0:00:00
Collecting nvidia-cuda-nvcc-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cuda_nvcc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (20.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 29.9 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 9.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12>=8.9 (from jax[cuda12_pip])
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 3.5 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 14.5 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 6.7 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12 (from jax[cuda12_pip])
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 10.5 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in ./jax_env/lib/python3.8/site-packages (from importlib-metadata>=4.6->jax[cuda12_pip]) (3.15.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12->jax[cuda12_pip])
  Downloading nvidia_nvjitlink_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (19.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 37.9 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jaxlib, jax, nvidia-cusolver-cu12
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.4.7+cuda11.cudnn86
    Uninstalling jaxlib-0.4.7+cuda11.cudnn86:
      Successfully uninstalled jaxlib-0.4.7+cuda11.cudnn86
  Attempting uninstall: jax
    Found existing installation: jax 0.4.8
    Uninstalling jax-0.4.8:
      Successfully uninstalled jax-0.4.8
Successfully installed jax-0.4.11 jaxlib-0.4.11+cuda12.cudnn88 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvcc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nvjitlink-cu12-12.1.105
```
Here you can see that jax.devices is only recognizing 1 of the gpu (or at least that's what you'd think)
```
(jax_env) willb@ip-26-0-130-134:~$ python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> jax.devices()
[gpu(id=0)]
>>> jax.numpy.array(0)
Array(0, dtype=int32, weak_type=True)```

### What jax/jaxlib version are you using?

0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info

_No response_

### NVIDIA GPU info

_No response_

**Comment by hawkinsp** [comment]
Can you confirm you don't have `CUDA_VISIBLE_DEVICES` set in your enviroment?

**Comment by wbrenton** [comment]
Setting it resolved the problem, thank you!

**Comment by hawkinsp** [comment]
Closing, since that seems like it's working as intended.
