### ISSUE TITLE
RuntimeError: Internal: Could not find the corresponding function

### ISSUE THREAD

**Issue by Dharmendra04** [google/jax#16546]
### Description

2023-06-23 23:37:35.895800: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-06-23 23:37:35.895810: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas
2023-06-23 23:37:35.900649: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "compare_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2023-06-23 23:37:35.900672: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function
Traceback (most recent call last):
  File "stage1.py", line 325, in <module>
    write_floatpoint_image(samples_dir+"/training_image_sample.png",images[0])
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5010, in _rewriting_take
    unique_indices)
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5018, in _gather
    indexer = _index_to_gather(shape(arr), idx)  # shared with _scatter_update
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5209, in _index_to_gather
    i = _normalize_index(i, x_shape[x_axis]) if normalize_indices else i
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 4790, in _normalize_index
    lax.lt(index, _constant_like(index, 0)),
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 406, in lt
    return lt_p.bind(x, y)
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/core.py", line 603, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/interpreters/xla.py", line 249, in apply_primitive
    return compiled_fun(*args)
  File "/home/dharmendra/anaconda3/envs/mobilenerf/lib/python3.6/site-packages/jax/interpreters/xla.py", line 365, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Could not find the corresponding function

### What jax/jaxlib version are you using?

jax-0.2.17

### Which accelerator(s) are you using?

GPU

### Additional system info

python 3.6 & ubuntu 22.04

### NVIDIA GPU info

Fri Jun 23 23:39:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  Off |
| 40%   60C    P2   349W / 450W |  22755MiB / 24564MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1901      G   /usr/lib/xorg/Xorg                186MiB |
|    0   N/A  N/A      2067      G   /usr/bin/gnome-shell               38MiB |
|    0   N/A  N/A      2638      G   ...8/usr/lib/firefox/firefox      159MiB |
|    0   N/A  N/A     17339      C   python                          22348MiB |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
JAX 0.2.17 is a very old release at this point. Please install the current release (0.4.13).

You may be getting an old release because your Python version is below the minimum we support. We actually just dropped support for Python 3.8, so you should install Python 3.9 or newer to use JAX.

Hope that helps!

**Comment by Dharmendra04** [comment]
Yes you are right. It solved my problem. Thank you very much...
