### ISSUE TITLE
Sharded FFT with JIT gives incorrect results on GPU since 0.4.9

### ISSUE THREAD

**Issue by Findus23** [google/jax#16909]
### Description

(this is not the same issue as #15680, but it gives helpful information on this topic)

I am trying to calculate the 3D-FFT of a 1024^3 matrix using 2 GPUs. This should work using code similar to https://jax.readthedocs.io/en/latest/jax.experimental.custom_partitioning.html (but adapted to calculate a 3D-FFT instead of a 1D) or the JAX-only code from https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuFFTMp/JAX_FFT (as shared in #15680).

My code seems to give the correct result when not using JIT, when only using GPU devices or when not sharding the memory.
But in the combination I need (JIT with GPU on sharded memory), the results differ from the other results (and what scipy/numpy calculates).

main code as a minimal example:
```python
import os
from pathlib import Path

import jax
import numpy as np
import scipy
from jax import jit
from jax.experimental import mesh_utils
from jax.sharding import Mesh, PartitionSpec as P, NamedSharding

import sharded_fft_minimal as sharded_fft

os.environ['XLA_FLAGS'] = f'--xla_force_host_platform_device_count=2'

jax.config.update("jax_enable_x64", True)


def print_subset(x):
    print(x[0, :4, :4])


size = 4
# xs = jax.random.normal(jax.random.PRNGKey(0), (size, size, size), dtype=jax.numpy.complex64)
xs = jax.numpy.ones((size, size, size), dtype=jax.numpy.complex64)

x_np = np.asarray(xs)
out_ref = scipy.fft.fftn(x_np, workers=128)

devices = mesh_utils.create_device_mesh((2,))

mesh = Mesh(devices, axis_names=('gpus',))

with mesh:
    xshard = jax.device_put(xs, NamedSharding(mesh, P("gpus", None)))

    def two_fft(x):
        out = sharded_fft.fft(x)
        out = sharded_fft.fft_X(out)
        return out


    two_fft_jit = jit(
        two_fft,
        in_shardings=(NamedSharding(mesh, P("gpus", None))),
        out_shardings=(NamedSharding(mesh, P(None, "gpus")))
    )

    out = two_fft(xshard).block_until_ready()
    out_jit = two_fft_jit(xshard).block_until_ready()

    print("JAX output without JIT:")
    print_subset(out)
    print("JAX output with JIT:")
    print_subset(out_jit)
    print("Reference output:")
    print_subset(out_ref)

    is_equal = np.allclose(out_ref, out_jit, rtol=1.e-2, atol=1.e-4)

    print(f"Are the jax (JIT) and scipy results the same? {is_equal}")

    a = Path("compiled.txt")
    a.write_text(two_fft_jit.lower(xshard).compile().as_text())
```
with `shared_fft_minimal.py`:

```python
import jax
from jax.experimental.custom_partitioning import custom_partitioning
from jax.sharding import PartitionSpec as P, NamedSharding


def _fft(x):
    return jax.numpy.fft.fftn(x, axes=list(range(1, len(x.shape))))


def _fftX(x):
    return jax.numpy.fft.fft(x, axis=0)


def supported_sharding(sharding, shape):
    return NamedSharding(sharding.mesh, P("gpus",None))


def partition(arg_shapes, result_shape):
    result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    return _fft, supported_sharding(arg_shardings[0], arg_shapes[0]), (
        supported_sharding(arg_shardings[0], arg_shapes[0]),)


def infer_sharding_from_operands(arg_shapes, result_shape):
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    return supported_sharding(arg_shardings[0], arg_shapes[0])


def supported_sharding_X(sharding, shape):
    return NamedSharding(sharding.mesh, P(None, "gpus"))


def partition_X(arg_shapes, result_shape):
    result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    return _fftX, supported_sharding_X(arg_shardings[0], arg_shapes[0]), (
        supported_sharding_X(arg_shardings[0], arg_shapes[0]),)


def infer_sharding_from_operands_X(arg_shapes, result_shape):
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    return supported_sharding_X(arg_shardings[0], arg_shapes[0])


def fft(x):
    @custom_partitioning
    def _fft_(x):
        return _fft(x)

    _fft_.def_partition(
        infer_sharding_from_operands=infer_sharding_from_operands,
        partition=partition)
    return _fft_(x)


def fft_X(x):
    @custom_partitioning
    def _fft_(x):
        return _fftX(x)

    _fft_.def_partition(
        infer_sharding_from_operands=infer_sharding_from_operands_X,
        partition=partition_X)
    return _fft_(x)
```

When I run this on a host with 2 GPUs (with CPUs all three outputs are the same), I get:
```text
2023-07-31 18:28:38.496970: W external/xla/xla/service/gpu/nvptx_compiler.cc:698] The NVIDIA driver's CUDA version is 11.6 which is older than the ptxas CUDA version (11.8.89). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
JAX output without JIT:
[[64.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
JAX output with JIT:
[[32.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
Reference output:
[[64.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
Are the jax (JIT) and scipy results the same? False
```

<details><summary>HLO</summary>
<p>

```
HloModule jit_two_fft, is_scheduled=true, entry_computation_layout={(c64[2,4,4]{2,1,0})->c64[4,2,4]{2,1,0}}

%fused_computation (param_0.1: c64[2,2,2,4]) -> c64[2,4,4] {
  %param_0.1 = c64[2,2,2,4]{3,2,0,1} parameter(0)
  %bitcast.30 = c64[4,2,4]{2,1,0} bitcast(c64[2,2,2,4]{3,2,0,1} %param_0.1)
  ROOT %transpose.5 = c64[2,4,4]{2,1,0} transpose(c64[4,2,4]{2,1,0} %bitcast.30), dimensions={1,2,0}, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
}

%fused_computation.1 (param_0.4: c64[2,4,4]) -> c64[2,2,2,4] {
  %param_0.4 = c64[2,4,4]{2,1,0} parameter(0)
  %bitcast.32 = c64[2,2,2,4]{3,2,1,0} bitcast(c64[2,4,4]{2,1,0} %param_0.4)
  %transpose.6 = c64[2,2,2,4]{3,2,1,0} transpose(c64[2,2,2,4]{3,2,1,0} %bitcast.32), dimensions={1,0,2,3}, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
  ROOT %bitcast.31 = c64[2,2,2,4]{3,2,0,1} bitcast(c64[2,2,2,4]{3,2,1,0} %transpose.6), metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
}

ENTRY %main.6_spmd (param: c64[2,4,4]) -> c64[4,2,4] {
  %param = c64[2,4,4]{2,1,0} parameter(0), sharding={devices=[2,1,1]0,1}
  %fft.0 = c64[2,4,4]{2,1,0} fft(c64[2,4,4]{2,1,0} %param), fft_type=FFT, fft_length={4,4}, metadata={op_name="jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(4, 4)]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=7}
  %fusion.1 = c64[2,2,2,4]{3,2,0,1} fusion(c64[2,4,4]{2,1,0} %fft.0), kind=kLoop, calls=%fused_computation.1, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
  %all-to-all-start = ((c64[2,2,2,4]{3,2,0,1}), c64[2,2,2,4]{3,2,0,1}) all-to-all-start(c64[2,2,2,4]{3,2,0,1} %fusion.1), channel_id=1, replica_groups={{0,1}}, dimensions={1}, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}, backend_config={"is_sync":true}
  %all-to-all-done = c64[2,2,2,4]{3,2,0,1} all-to-all-done(((c64[2,2,2,4]{3,2,0,1}), c64[2,2,2,4]{3,2,0,1}) %all-to-all-start), channel_id=1, replica_groups={{0,1}}, dimensions={1}, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
  %fusion = c64[2,4,4]{2,1,0} fusion(c64[2,2,2,4]{3,2,0,1} %all-to-all-done), kind=kLoop, calls=%fused_computation, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
  %fft.1 = c64[2,4,4]{2,1,0} fft(c64[2,4,4]{2,1,0} %fusion), fft_type=FFT, fft_length={4}, metadata={op_name="jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(4,)]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=11}
  ROOT %transpose.4 = c64[4,2,4]{2,1,0} transpose(c64[2,4,4]{2,1,0} %fft.1), dimensions={2,0,1}, frontend_attributes={fingerprint_before_lhs="902ad6c9909648982a9ff9203157ab0d"}, metadata={op_name="jit(two_fft)/jit(main)/custom_partitioning[partition=<function partition_X at 0x1510182a8310> propagate_user_sharding=None infer_sharding_from_operands=<function infer_sharding_from_operands_X at 0x1510182a83a0> decode_shardings=True in_tree=PyTreeDef((*,)) out_tree=PyTreeDef(*) static_args=[]]" source_file="/jax-testing/sharded_fft_minimal.py" source_line=65}
}
```

</p>
</details> 

### What jax/jaxlib version are you using?

jax==0.4.14, jaxlib==0.4.14+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU (2x Nvidia A40)

### Additional system info

Python 3.9.15, AlmaLinux 8.5

### NVIDIA GPU info

```text
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 510.39.01    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:41:00.0 Off |                    0 |
|  0%   32C    P0    74W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          Off  | 00000000:A1:00.0 Off |                    0 |
|  0%   31C    P0    75W / 300W |      0MiB / 46068MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Findus23** [comment]
I also tried running the benchmark from [cuFFTMp](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuFFTMp/JAX_FFT) directly, but needed to change a few minor things so that imports work with my jax version and multiple GPUs on one host. 

When modifying this code block
https://github.com/NVIDIA/CUDALibrarySamples/blob/f299986ecc990c49dce295e345f9e3ad95ded188/cuFFTMp/JAX_FFT/tests/fft_test.py#L117-L122
to 
```python
start = time.time()
print("input:")
print(dinput)
x = dinput
for _ in range(cycles):
    x = fwd_bwd_bench(x)
    print("x:")
    print(x)
    print("numpy:")
    print(numpy.fft.ifftn(numpy.fft.fftn(input)))
doutput = x.block_until_ready()
stop = time.time()
```

I also get different results between numpy and jax FFT:
```text
input:
[[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]]
x:
[[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]]
numpy:
[[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]]
```
and the same results when replacing `fwd_bwd_pjit` with `fwd_bwd`

**Comment by Findus23** [comment]
Another test shows that the incorrect result differs strongly by datatype:

With the above code updated to 
```python
# jax.config.update("jax_enable_x64", True)
xs = jax.random.normal(
    jax.random.PRNGKey(0),
    (size, size, size),
    dtype=jax.numpy.complex64
)
```
I get 
```text
JAX output without JIT:
[[ 4.6250744  +1.655502j   -0.8575981  -2.2615793j
  -8.510313   +7.1343594j   7.286973   -5.468896j  ]
 [ 5.747694   +2.854593j    8.017227  -12.640258j
   2.4195366  +9.599846j    2.3991098  -6.2334623j ]
 [ 0.05215216 +7.5721874j  -8.085979   -3.6076527j
  -0.29224873 +0.36597013j -7.8748264  -5.073735j  ]
 [ 6.603516  +12.5646515j  -0.58227634 +5.071442j
  -9.074454   +0.47400856j  4.6850696  +5.99322j   ]]
JAX output with JIT:
[[-2.0321913e+00+1.5058144e+01j  4.2970805e+00-9.6251125e+00j
  -7.3626089e+00+1.5319314e+01j  1.4256954e+01-6.5427341e+00j]
 [ 1.2095287e+01+1.6869164e+01j -6.7879229e+00+9.4263554e-03j
  -2.0586638e+00+9.6544361e+00j -7.8202343e+00-9.4283175e-01j]
 [-6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j
  -6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j]
 [-6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j
  -6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j]]
Reference output:
[[ 4.6250744  +1.6555014j  -0.8575978  -2.261579j
  -8.510313   +7.1343594j   7.2869735  -5.4688964j ]
 [ 5.747694   +2.854593j    8.017227  -12.640258j
   2.4195373  +9.599846j    2.3991096  -6.2334623j ]
 [ 0.05215228 +7.5721874j  -8.085979   -3.6076522j
  -0.2922498  +0.3659699j  -7.8748283  -5.0737348j ]
 [ 6.6035166 +12.5646515j  -0.5822754  +5.0714417j
  -9.074454   +0.47400856j  4.6850705  +5.9932194j ]]
```
And with 64bit:
```python
jax.config.update("jax_enable_x64", True)
xs = jax.random.normal(
    jax.random.PRNGKey(0),
    (size, size, size),
    dtype=jax.numpy.complex128
)
```
it becomes:
```text
JAX output without JIT:
[[  4.53110121 -5.42857443j   2.823367   -9.09603099j
    7.28474582-11.47654029j   1.99185486 +1.74253872j]
 [  6.93847013 -2.95786878j -16.05594063 -3.47812555j
   -5.68283733 -1.55930829j  -2.23199019 +6.66552633j]
 [  2.74730892 -2.34144991j -12.500137   -3.62033921j
    7.45987686 +4.74912884j  10.95039256 -4.19533421j]
 [ -4.09811938 +3.48808763j  -8.19007414 +1.73404671j
   -0.80590044 -4.69896172j   2.15027043 -9.17528198j]]
JAX output with JIT:
[[ 8.40507180e+000-2.43439964e+000j  1.76275197e+001-1.98252892e+000j
   3.77844995e+000-9.01459259e+000j -5.32531468e+000+2.21369021e+000j]
 [ 4.85005727e+000-8.36303426e+000j -1.43999323e+001+6.71514992e+000j
   1.23173687e+001-5.39414742e+000j  8.30568192e+000+5.77396391e+000j]
 [-1.08187595e+301+1.84421548e+022j  2.34007863e+266-3.90630795e+173j
   1.00342272e+265-5.57232292e+000j -7.10074304e+000-2.21372768e+165j]
 [-1.31710865e+202-1.51260176e+229j -7.92660879e+225+5.34813502e+222j
  -1.70851517e+132+6.65772753e+138j -6.18259311e+144+4.89858632e+000j]]
Reference output:
[[  4.53110121 -5.42857443j   2.823367   -9.09603099j
    7.28474582-11.47654029j   1.99185486 +1.74253872j]
 [  6.93847013 -2.95786878j -16.05594063 -3.47812555j
   -5.68283733 -1.55930829j  -2.23199019 +6.66552633j]
 [  2.74730892 -2.34144991j -12.500137   -3.62033921j
    7.45987686 +4.74912884j  10.95039256 -4.19533421j]
 [ -4.09811938 +3.48808763j  -8.19007414 +1.73404671j
   -0.80590044 -4.69896172j   2.15027043 -9.17528198j]]
```

Also checking the full 4x4x4 array in the first case shows quite a few entries that are zero or repeating:
<details><summary>Full Array</summary>
<p>

```text
[[[-2.0321913e+00+1.5058144e+01j  4.2970805e+00-9.6251125e+00j
   -7.3626089e+00+1.5319314e+01j  1.4256954e+01-6.5427341e+00j]
  [ 1.2095287e+01+1.6869164e+01j -6.7879229e+00+9.4263554e-03j
   -2.0586638e+00+9.6544361e+00j -7.8202343e+00-9.4283175e-01j]
  [-6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j
   -6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j]
  [-6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j
   -6.4622705e+33-6.4622705e+33j -6.4622705e+33-6.4622705e+33j]]

 [[-3.7904797e+00-1.9218649e+01j  4.0303049e+00+1.2647402e-01j
    2.0930943e+00+4.8396072e+00j  9.0125875e+00-3.9036689e+00j]
  [-6.8532133e-01+1.6853342e+00j -5.8682117e+00-2.1767204e+01j
    1.4586600e+01+1.3182940e+01j  1.1533028e+01-1.8864393e+01j]
  [-6.4622705e+33+0.0000000e+00j -6.4622705e+33+0.0000000e+00j
   -6.4622705e+33+0.0000000e+00j -6.4622705e+33+0.0000000e+00j]
  [-6.4622705e+33+0.0000000e+00j -6.4622705e+33+0.0000000e+00j
   -6.4622705e+33+0.0000000e+00j -6.4622705e+33+0.0000000e+00j]]

 [[ 1.9365990e+01+1.1662802e+01j  7.6619020e+00+8.4834232e+00j
   -4.8324118e+00-9.3418112e+00j -4.5125694e+00-1.8177962e-01j]
  [-4.2745185e+00+4.4168015e+00j  2.2013352e+00+7.6215229e+00j
   -3.9565558e+00+1.8024149e+01j -9.3683624e+00+8.8611822e+00j]
  [ 0.0000000e+00+0.0000000e+00j  0.0000000e+00+0.0000000e+00j
    0.0000000e+00+0.0000000e+00j  0.0000000e+00+0.0000000e+00j]
  [ 0.0000000e+00+0.0000000e+00j  0.0000000e+00+0.0000000e+00j
    0.0000000e+00+0.0000000e+00j  0.0000000e+00+0.0000000e+00j]]

 [[-5.2897873e+00-4.3190117e+00j -1.6217491e+01+3.6025798e-01j
    1.2814125e+01-1.4356110e+01j -1.5521908e-01-1.3899309e+01j]
  [ 1.0835196e+01-6.8513775e-01j  1.5637071e+00+1.4616768e+01j
    1.1689168e+01-5.9961653e-01j  2.1295629e+00-4.7527847e+00j]
  [ 0.0000000e+00-6.4622705e+33j  0.0000000e+00-6.4622705e+33j
    0.0000000e+00-6.4622705e+33j  0.0000000e+00-6.4622705e+33j]
  [ 0.0000000e+00-6.4622705e+33j  0.0000000e+00-6.4622705e+33j
    0.0000000e+00-6.4622705e+33j  0.0000000e+00-6.4622705e+33j]]]
```

</p>
</details>

**Comment by Findus23** [comment]
Okay, I just tried out version 0.4.8 (as it is the oldest one I could easily install with `jax[cuda11_pip]`) and interestingly enough, it works correctly.

I just needed to slightly change the above script to adapt to the older function arguments:
```diff
diff --git a/sharded_fft_minimal.py b/sharded_fft_minimal_old.py
index 3c870a4..dd907f5 100644
--- a/sharded_fft_minimal.py
+++ b/sharded_fft_minimal_old.py
@@ -15,15 +15,12 @@ def supported_sharding(sharding, shape):
     return NamedSharding(sharding.mesh, P("gpus",None))
 
 
-def partition(arg_shapes, result_shape):
-    result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
-    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
+def partition(arg_shapes, arg_shardings, result_shape, result_sharding):
     return _fft, supported_sharding(arg_shardings[0], arg_shapes[0]), (
         supported_sharding(arg_shardings[0], arg_shapes[0]),)
 
 
-def infer_sharding_from_operands(arg_shapes, result_shape):
-    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
+def infer_sharding_from_operands(arg_shapes, arg_shardings, shape):
     return supported_sharding(arg_shardings[0], arg_shapes[0])
 
 
@@ -31,15 +28,12 @@ def supported_sharding_X(sharding, shape):
     return NamedSharding(sharding.mesh, P(None, "gpus"))
 
 
-def partition_X(arg_shapes, result_shape):
-    result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
-    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
+def partition_X(arg_shapes, arg_shardings, result_shape, result_sharding):
     return _fftX, supported_sharding_X(arg_shardings[0], arg_shapes[0]), (
         supported_sharding_X(arg_shardings[0], arg_shapes[0]),)
 
 
-def infer_sharding_from_operands_X(arg_shapes, result_shape):
-    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
+def infer_sharding_from_operands_X(arg_shapes, arg_shardings, shape):
     return supported_sharding_X(arg_shardings[0], arg_shapes[0])
```

Testing all newer versions seems to indicate that already 0.4.9 is broken in the same way.
So I guess something in https://github.com/google/jax/compare/jax-v0.4.8...jax-v0.4.9 or a different XLA version causes this issue.

**Comment by Findus23** [comment]
I finally got jax to compile from source on my system and was able to bisect the exact xla-commit that broke this code:

It turns out that using jax 0.4.9 and jaxlib 0.4.7, everything works. But with jaxlib 0.4.9 the above issue occurs.
And it turns out the issue is in XLA as compiling jaxlib 0.4.9 with https://github.com/openxla/xla/commit/dad64948516e3672b3e2518945831a70b5e90b81 is broken (as expected), but the same jax/jaxlib with https://github.com/openxla/xla/commit/79ca8d03c296ede04dc9a86ce9dde79ed909dda8 works.

From there I could bisect all commits in https://github.com/openxla/xla/compare/79ca8d03c296ede04dc9a86ce9dde79ed909dda8...dad64948516e3672b3e2518945831a70b5e90b81 and it turns out the first broken commit is https://github.com/openxla/xla/commit/8680d1bad06d45396b171793d936ea71065c7107 or https://github.com/openxla/xla/pull/2778 (with https://github.com/openxla/xla/commit/9d244bfa91793c4c58ddf82ffaebb5c505b2da07 being the last working commit).

<details><summary>Test Details</summary>
<p>

```text
$ pip install tmp/jaxlib-9d244bfa-0.4.9-cp39-cp39-manylinux2014_x86_64.whl --force
[...]
$ python test_minimal_old.py jax version 0.4.9
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1694451732.594824 1486184 tfrt_cpu_pjrt_client.cc:445] TfrtCpuClient created.
4.7570 / 4.7570: start
6.1209 / 1.3638: fft_jit run
6.6493 / 0.5284: fft finished
JAX output with JIT:
[[ 8.3883450e+06   +0.j        3.3468820e+02 +386.0061j
   6.7245923e+02-2043.2562j   -1.9714886e+02-1012.20386j ]
 [-6.1117786e+02 +224.31882j   4.6303351e+02 -974.9061j
   3.8815759e+02 +610.24756j   1.1820348e+03  -40.36635j ]
 [ 3.5503680e+02 -305.97424j  -1.9115245e+02-1535.6515j
   4.1164917e+01  +86.547005j -1.4985818e+02 +250.45987j ]
 [-8.6542932e+02 +775.30206j  -2.0335649e+02+1296.3466j
  -1.0643232e+03 +225.98059j  -1.3763538e+03 -738.6568j  ]]
Reference output:
[[ 8.38834515e+06   -0.j          3.34689661e+02 +386.00554251j
   6.72462030e+02-2043.25471474j -1.97148671e+02-1012.20381339j]
 [-6.11177902e+02 +224.31882354j  4.63033443e+02 -974.90613044j
   3.88157682e+02 +610.24784839j  1.18203458e+03  -40.36616595j]
 [ 3.55036784e+02 -305.97435746j -1.91152509e+02-1535.65147145j
   4.11648390e+01  +86.54715244j -1.49858053e+02 +250.45974427j]
 [-8.65429421e+02 +775.30192023j -2.03356435e+02+1296.34653685j
  -1.06432337e+03 +225.98059439j -1.37635384e+03 -738.65675133j]]
Are the jax (JIT) and scipy results the same? True
I0000 00:00:1694451739.560787 1486184 tfrt_cpu_pjrt_client.cc:448] TfrtCpuClient destroyed.
$ pip install tmp/jaxlib-8680d1b-0.4.9-cp39-cp39-manylinux2014_x86_64.whl --force
[...]
$ python test_minimal_old.py jax version 0.4.9
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1694452019.944300 1487907 tfrt_cpu_pjrt_client.cc:445] TfrtCpuClient created.
4.7255 / 4.7255: start
7.4376 / 2.7121: fft_jit run
7.9355 / 0.4979: fft finished
JAX output with JIT:
[[ 6.2947845e+06   +0.j       2.1749468e+03 +319.78992j
   1.2456562e+03+2438.8867j   9.2939832e+02 +329.0697j ]
 [-8.6273816e+02 -811.44666j  1.4054868e+02 +585.1288j
  -6.2169360e+02-1246.3406j  -2.4191275e+02+1264.7472j ]
 [-7.0989075e+02-1084.596j    9.6910162e+02 -591.3728j
  -7.3031091e+02 -601.01984j  9.0614209e+02  +80.99515j]
 [ 6.9135394e+02 +300.6054j   7.7462994e+02-1490.218j
  -1.3380891e+03 -425.75577j  8.3488062e+02 +615.5832j ]]
Reference output:
[[ 8.38968949e+06   -0.j          3.53973220e+02 -588.75971071j
   6.06135765e+02 +857.65845664j  3.16912375e+02 +726.83423305j]
 [-1.28798081e+02 +133.87261708j -1.05350562e+03 +581.77241821j
   2.56638558e+02 -946.75897686j  3.17061442e+02 +238.45195598j]
 [-1.09668213e+03-1078.57225684j  3.88102428e+02 -356.94145411j
  -1.12851382e+03 -843.19431105j  7.73129891e+02-1721.19615227j]
 [ 6.82739483e+02 +835.9835899j   8.84505658e+02-1299.3917609j
  -2.11410959e+03 +411.73759055j  4.84705677e+02 -459.79164364j]]
Are the jax (JIT) and scipy results the same? False
I0000 00:00:1694452028.261661 1487907 tfrt_cpu_pjrt_client.cc:448] TfrtCpuClient destroyed.
```

</p>
</details> 

(side-note: I had to cherry-pick https://github.com/openxla/xla/commit/be1cee3e4aeee55ea5487d15398d92d9e21e19b2 on every commit to make it compile on my setup)

Unfortunately I don't understand XLA enough to know how removing that optimization pass broke jax here. Maybe @jurahul has a good idea here, I would be really thankful.

But to double-check this is correct, I went back to https://github.com/openxla/xla/commit/dad64948516e3672b3e2518945831a70b5e90b81 and reverted https://github.com/openxla/xla/commit/8680d1bad06d45396b171793d936ea71065c7107 there and the resulting jaxlib (that should be identical to the released 0.4.9 apart from that change) indeed works correctly. Applying it to the latest jax/xla version doesn't seem that easy as the related code changed a bit since.
And the CPU code still contains this optimization pass which might explain why this issue only occurs on GPUs:
https://github.com/openxla/xla/blob/dad64948516e3672b3e2518945831a70b5e90b81/xla/service/cpu/cpu_compiler.cc#L625

**Comment by jurahul** [comment]
Thanks. AllToAll in XLA has a mode where it first splits all inputs into N chunks (N = # of devices) and then concatenates all Chunk[0] across all device on device 0, Chunk[1] across all devices on device 1 etc. XLA/GPU at some point did not support this in the backend, so the pass in question was used to decompose such AllToAlls into other collectives. However, XLA/GPU later added support for such AllToAlls in the backend, but the pass remained. The changes in question were to remove these expansion that was not needed. 

I suspect this code is exposing a potential correctness issue in our AllToAll implementation with spit dims.

**Comment by andy-kogsys** [comment]
@Findus23 thanks for sharing your excellent work. I'm facing the same problem, but your post has saved me a lot of time.

@jurahul thanks for the update. Do you know if anyone is working on the AllToAll issue you described?

**Comment by Findus23** [comment]
I looked into this issue again as it is frustrating having to use an outdated jax version to get correct results. Starting with jax 0.4.16 the reproduction script has to be slightly adapted to accommodate to https://github.com/google/jax/pull/17072.

```diff
diff --git a/sharded_fft_minimal.py b/sharded_fft_minimal_newest.py
index 6a44d14..17eb685 100644
--- a/sharded_fft_minimal.py
+++ b/sharded_fft_minimal_newest.py
@@ -15,14 +15,14 @@ def supported_sharding(sharding, shape):
     return NamedSharding(sharding.mesh, P("gpus", None))
 
 
-def partition(arg_shapes, result_shape):
+def partition(mesh, arg_shapes, result_shape):
     result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
     arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
-    return _fft, supported_sharding(arg_shardings[0], arg_shapes[0]), (
+    return mesh, _fft, supported_sharding(arg_shardings[0], arg_shapes[0]), (
         supported_sharding(arg_shardings[0], arg_shapes[0]),)
 
 
-def infer_sharding_from_operands(arg_shapes, result_shape):
+def infer_sharding_from_operands(mesh, arg_shapes, result_shape):
     arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
     return supported_sharding(arg_shardings[0], arg_shapes[0])
 
@@ -31,14 +31,14 @@ def supported_sharding_X(sharding, shape):
     return NamedSharding(sharding.mesh, P(None, "gpus"))
 
 
-def partition_X(arg_shapes, result_shape):
+def partition_X(mesh, arg_shapes, result_shape):
     result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
     arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
-    return _fftX, supported_sharding_X(arg_shardings[0], arg_shapes[0]), (
+    return mesh, _fftX, supported_sharding_X(arg_shardings[0], arg_shapes[0]), (
         supported_sharding_X(arg_shardings[0], arg_shapes[0]),)
 
 
-def infer_sharding_from_operands_X(arg_shapes, result_shape):
+def infer_sharding_from_operands_X(mesh, arg_shapes, result_shape):
     arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
     return supported_sharding_X(arg_shardings[0], arg_shapes[0])
```

I checked all jax version since I created this issue and it turns out that while jax+jaxlib 0.4.18 still shows the exact same issue, 0.4.19 seems to give correct results.

I will need to do more testing, but as nothing in [the changelog](https://github.com/google/jax/blob/main/CHANGELOG.md) seems related, I guess some change in XLA fixed this.

@andy-kogsys You might also want to try this out again with jax+jaxlib 0.4.19

**Comment by hawkinsp** [comment]
I strongly suspect the fix for https://github.com/google/jax/issues/18122, which is in 0.4.19, also fixed this issue.

**Comment by Findus23** [comment]
After a bit of testing it seems like the bug is indeed solved.

For everyone interested in 3d FFTs stumbling over this post, I have now also updated my reference code for the latest jax version:
https://gist.github.com/Findus23/eb5ecb9f65ccf13152cda7c7e521cbdd

**Comment by andy-kogsys** [comment]
All working for me. Thank you both for all your help, this is a real enabler for anything requiring large FFTs. 

@Findus23 , one small comment, the code in the link above still appears to be targeted at 0.4.9, as the partitioning arguments are the old style. For example:
`def partition(arg_shapes, arg_shardings, result_shape, result_sharding):
    ...`


instead of:
`def partition(mesh, arg_shapes, result_shape):
    ...`

I got it working with the mods you mentioned on October 23rd though.

Thanks again!
