### ISSUE TITLE
Scan with indexing wrong result on gpu

### ISSUE THREAD

**Issue by inailuig** [google/jax#17003]
### Description

Recently I wrote a searchsorted function which works on multidimensional arrays, and I noticed that I was getting wrong results on gpu.

Here is a minimal reproducer, where the wrong result is introduced somewhere in the `jax.lax.fori_loop`.

```python3
import jax
import jax.numpy as jnp
import numpy as np
from functools import partial

print(jax.devices())

def le2(k1, k2):
    assert k1.shape == k2.shape
    assert k1.shape[-1] == 2
    assert k2.shape[-1] == 2
    return (k1[..., 0] < k2[..., 0]) | ( (k1[..., 0] == k2[..., 0]) & (k1[..., 1] <= k2[..., 1]))


@partial(jax.jit, static_argnames='dtype')
def searchsorted_via_scan(sorted_arr, query, dtype=jnp.int32):
    assert sorted_arr.ndim == 2
    assert query.shape[-1] == sorted_arr.shape[-1]

    def body_fun(_, state):
        low, high = state
        mid = jax.lax.div(low + high, dtype(2))
        go_left = le2(query, sorted_arr[mid])
        return jax.lax.select(go_left, low, mid), jax.lax.select(go_left, mid, high)

    n = len(sorted_arr)
    n_levels = int(np.ceil(np.log2(n + 1)))
    shape = query.shape[:-1]
    init = jnp.full(shape, dtype(0)), jnp.full(shape, dtype(n))
    return jax.lax.fori_loop(0, n_levels, body_fun, init)[1]

n = 4
i = jnp.arange(n, dtype=jnp.int32)
# i is the sorted_arr
i = jnp.concatenate(jnp.broadcast_arrays(i[:, None, None], i[None, :, None]), axis=-1).reshape(-1, 2)
# query the first 3 elements
j = i[:3]

# gpu with jit
res_gpu_jit = searchsorted_via_scan(i,j)
print('gpu,jit', res_gpu_jit)

# gpu without jit
with jax.disable_jit():
    res_gpu_nojit = searchsorted_via_scan(i,j)
print('gpu,no jit', res_gpu_nojit)

#cpu
res_cpu = jax.jit(searchsorted_via_scan, backend='cpu')(i,j)
print('cpu', res_cpu)
```
and I get the output
```
[gpu(id=0)]
gpu,jit [16 16 16]
gpu,no jit [0 1 2]
cpu [0 1 2]
```
whereas I would expect `[0 1 2]` also on the gpu when under jit.

Going back I believe it this bug was introduced somewhere between jax/jaxlib 0.4.4 (correct result) and 0.4.6 (wrong result). 
I also tried with jaxlib and xla compiled from head (both from this afternoon), but the bug still appears.

### What jax/jaxlib version are you using?

jax/jaxlib 0.4.14

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

```Mon Aug  7 16:07:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+```

**Comment by jakevdp** [comment]
Thanks for the clear report – digging a bit further I found that this is due to the `le2` function acting differently under JIT:
```python
import jax
import jax.numpy as jnp

def le2(x, y):
    return (x[0] < y[0]) | ((x[0] == y[0]) & (x[1] <= y[1]))

x = jnp.array([0, 1])
y = jnp.array([0, 0])

print(le2(x, y))
# False
print(jax.jit(le2)(x, y))
# True
```
Where we see the incorrect result only on GPU. I suspect there's some sort of algebraic simplification of boolean operators to blame.

**Comment by inailuig** [comment]
Thanks for the quick answer, actually it seems to be caused by the `<`.
If I instead use not and >= it works, i.e. :
```python
def le2(x, y):
    return ~(x[0] >= y[0]) | ((x[0] == y[0]) & (x[1] <= y[1]))
 ```

**Comment by jakevdp** [comment]
Reported upstream in https://github.com/openxla/xla/issues/4803

**Comment by inailuig** [comment]
@jakevdp I just checked with jaxlib compiled with xla from head and it is indeed fixed now.
I would be happy for this issue to be closed as soon as xla gets updated in jax.

**Comment by jakevdp** [comment]
Thanks for checking that this fixes the issue! The XLA fix should make it into the next jaxlib release.
