### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError

### ISSUE THREAD

**Issue by xueminchi** [google/jax#17976]
### Description

The test program
```
import jax
import jax.numpy as jnp
n = 1
l = 0
T = (2*l+1)*jnp.pi/2*(jnp.sqrt(n+1)+jnp.sqrt(n))
```

The error messages:
```
/home/cxm/anaconda3/envs/jax_study/bin/python /home/cxm/PycharmProjects/jax_play/test01.py 
2023-10-06 13:14:53.374940: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:232] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-10-06 13:14:53.374951: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:235] Used ptxas at ptxas
2023-10-06 13:14:53.424902: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:864] failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
2023-10-06 13:14:53.424917: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:869] error log buffer (63 bytes): error   : Binary format for key='0', ident='' is not recognize
2023-10-06 13:14:53.424927: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
2023-10-06 13:14:53.424942: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2711] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=0#.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cxm/PycharmProjects/jax_play/test01.py", line 5, in <module>
    T = (2*l+1)*jnp.pi/2*(jnp.sqrt(n+1)+jnp.sqrt(n))
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid; current tracing scope: fusion; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=0#.
```

This is a new environment with the installed packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
importlib-metadata        6.8.0                    pypi_0    pypi
jax                       0.4.17                   pypi_0    pypi
jaxlib                    0.4.17+cuda12.cudnn89          pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libnsl                    2.0.0                hd590300_1    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ml-dtypes                 0.3.1                    pypi_0    pypi
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.26.0                   pypi_0    pypi
nvidia-cublas-cu12        12.2.5.6                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.2.142                 pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.2.140                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.2.140                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.2.140                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.4.25                 pypi_0    pypi
nvidia-cufft-cu12         11.0.8.103               pypi_0    pypi
nvidia-cusolver-cu12      11.5.2.141               pypi_0    pypi
nvidia-cusparse-cu12      12.1.2.141               pypi_0    pypi
nvidia-nvjitlink-cu12     12.2.140                 pypi_0    pypi
openssl                   3.1.3                hd590300_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.9.18          h0755675_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.11.3                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0                   pypi_0    pypi
```

By running `nvcc --version `
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

cuDNN version:
```
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 9
#define CUDNN_PATCHLEVEL 4
```

By running `echo $LD_LIBRARY_PATH | grep /usr/local/cuda-12.2/lib64`
`/usr/lib/x86_64-linux-gnu:/usr/local/cuda-12.2/lib64:
`
By running `echo $PATH | grep /usr/local/cuda-12.2/bin`
`/usr/local/cuda-12.2/bin:/home/cxm/anaconda3/bin:/home/cxm/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
`

### What jax/jaxlib version are you using?

jax v0.4.17, 0.4.17+cuda12.cudnn89 

### Which accelerator(s) are you using?

GPU

### Additional system info

python 3.9. cuda 12.2, cuDnn, 8.9.4

### NVIDIA GPU info

<pre>+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P0              N/A / 100W |      9MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2178      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
</pre>

**Comment by hawkinsp** [comment]
Is `ptxas` in your PATH? Can you remove it from your `PATH`? (`which ptxas`)

If `ptxas` is present in `PATH`, it will override the version installed in the `nvidia-cuda-nvcc-cu12` pip package.

**Comment by xueminchi** [comment]
> Is `ptxas` in your PATH? Can you remove it from your `PATH`? (`which ptxas`)
> 
> If `ptxas` is present in `PATH`, it will override the version installed in the `nvidia-cuda-nvcc-cu12` pip package.

At first, I run `which ptxas`, and I get
`/usr/local/cuda-12.2/bin`
The way I remove it is to delete the` /usr/local/cuda-12.2/bin` in `PATH`

Then I run `which ptxas` again, and I get
`/usr/bin/ptxas`

Do I need to remove it again? I'm a little confused here.

**Comment by xueminchi** [comment]
This problem has been solved.
The issue comes from the multiple CUDA Toolkits on my Ubuntu 22.04 system. I deleted them all and installed CUDA Toolkit 11.8, everything works fine.

**Comment by guruace** [comment]
> This problem has been solved. The issue comes from the multiple CUDA Toolkits on my Ubuntu 22.04 system. I deleted them all and installed CUDA Toolkit 11.8, everything works fine. For more details, confused readers can @ me.

@xueminchi Sounds good. I had the similar issue. The Error was:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rbhuang/materials_discovery/model/gnome.py", line 28, in <module>
    from jax_md import util
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax_md/__init__.py", line 27, in <module>
    from jax_md import rigid_body
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax_md/rigid_body.py", line 1009, in <module>
    monomer = point_union_shape(onp.array([[0.0, 0.0]], f32), f32(1.0))
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 148, in __call__
    return asarray(x, dtype=self.dtype)
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2201, in asarray
    return array(a, dtype=dtype, copy=False, order=order)  # type: ignore
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2166, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 402, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 405, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 893, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/dispatch.py", line 87, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: XLA requires ptxas version 11.8 or higher

**Comment by Deroes** [comment]
> > This problem has been solved. The issue comes from the multiple CUDA Toolkits on my Ubuntu 22.04 system. I deleted them all and installed CUDA Toolkit 11.8, everything works fine. For more details, confused readers can @ me.
> 
> @xueminchi Sounds good. I had the similar issue. The Error was:
> 
> jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/rbhuang/materials_discovery/model/gnome.py", line 28, in from jax_md import util File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax_md/**init**.py", line 27, in from jax_md import rigid_body File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax_md/rigid_body.py", line 1009, in monomer = point_union_shape(onp.array([[0.0, 0.0]], f32), f32(1.0)) File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 148, in **call** return asarray(x, dtype=self.dtype) File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2201, in asarray return array(a, dtype=dtype, copy=False, order=order) # type: ignore File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2166, in array out_array: Array = lax_internal._convert_element_type( File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type return convert_element_type_p.bind(operand, new_dtype=new_dtype, File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 402, in bind return self.bind_with_trace(find_top_trace(args), args, params) File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 405, in bind_with_trace out = trace.process_primitive(self, map(trace.full_raise, args), params) File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/core.py", line 893, in process_primitive return primitive.impl(*tracers, **params) File "/home/rbhuang/miniforge3/envs/GNoME/lib/python3.10/site-packages/jax/_src/dispatch.py", line 87, in apply_primitive outs = fun(*args) jaxlib.xla_extension.XlaRuntimeError: INTERNAL: XLA requires ptxas version 11.8 or higher

oh，I have the same problem, please let me know if it is solved

**Comment by JHUNAI** [comment]
In my opinion, you can add the 
export PATH="/usr/local/cuda-12.3/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-12.3/lib64:$LD_LIBRARY_PATH"
path of CUDA to your "~/.bashrc ", and Execute "source ~/.bashrc". Finally, restart the environment and it will be ok
