### ISSUE TITLE
Device Kernal invalid for batched learning  INTERNAL: Failed to load in-memory CUBIN (compiled for a different GPU?).: CUDA_ERROR_INVALID_IMAGE

### ISSUE THREAD

**Issue by samskiter** [google/jax#19148]
### Description

This issue seems to be related to an out-of-memory problem, but I'm getting a very strange error instead.

My program is batching a dataset and this issue only occurs when the batches are longer than a certain length (see below, I did a little bit of experimenting on model size vs max-batch)

Error is:
```
2023-12-31 09:40:29.870918: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2732] Execution of replica 0 failed: INTERNAL: Failed to load in-memory CUBIN (compiled for a different GPU?).: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

THIS DOESN'T WORK
``` python3

jax.config.update("jax_enable_x64", True) # I'm using 64 bit mode but this makes *no* difference

def fit_with_batched_adjoint_method(
        self, theta: jax.Array, max_batch_size: int
    ) -> jax.Array:
        # break the problem into batches

        previous_correction = jnp.zeros_like(theta)

        num_batches = (
            len(self.list_target_system_states) + max_batch_size - 1
        ) // max_batch_size
        # calculate the adjusted batch size
        adjusted_batch_size = (
            len(self.list_target_system_states) + num_batches - 1
        ) // num_batches
        adjusted_batch_size = 32 # overriding max_batch_size for narrowing this bug down <- changing to 31 works
        print(f"num_batches: {num_batches}, adjusted_batch_size: {adjusted_batch_size}")
        # create batches
        batches = [
            slice(i, i + adjusted_batch_size)
            for i in range(0, len(self.list_target_system_states), adjusted_batch_size)
        ]
        # correct the last batch
        batches[-1] = slice(
            batches[-1].start, len(self.list_target_system_states) - 1
        )  # type: ignore[assignment]
        x: jax.Array = jnp.ones(
            len(self.graph.get_latents()) * len(self.list_target_system_states)
        )

        # initial fit batch, by batch:
        for idx, batch in enumerate(batches):
            x_batch_slice = slice(
                batch.start * len(self.graph.get_latents()),
                batch.stop * len(self.graph.get_latents()),
            )
            target_system_states_batch = self.list_target_system_states[batch]
            x_batch = x[x_batch_slice]
            x_batch = ParametricPiecesFitter.calculate_x_pure( # ERROR OCCURS HERE (calculate_x_pure is a static, Jitted method)
                target_system_states_batch, x_batch
            )
            x = jax.lax.dynamic_update_slice(x, x_batch, (x_batch_slice.start,))
            print(f"initial fit batch {idx} done")
        print("initial fit done")

        # ... rest of the algorithm
```

Weirdly, though - using the entire dataset works just fine - even though it's something like 250 datapoints:

THIS DOES WORK - No batching so more data
``` python3

jax.config.update("jax_enable_x64", True)  # type: ignore[no-untyped-call]

def fit_with_adjoint_method(self, theta: jax.Array) -> jax.Array:
        jax.numpy.set_printoptions(threshold=sys.maxsize)
        previous_correction = jnp.zeros_like(theta)
        x = jnp.ones(
            len(self.graph.get_latents()) * len(self.list_target_system_states)
        )
        # initial fit:
        x = ParametricPiecesFitter.calculate_x_pure(
            self.list_target_system_states, x
        )
        print("initial fit done")

        # ... rest of the algorithm
```

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

GPU

### Additional system info?

```1.26.2 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] uname_result(system='Linux', node='double-trouble', release='5.10.0-26-cloud-amd64', version='#1 SMP Debian 5.10.197-1 (2023-09-29)', machine='x86_64')```

### NVIDIA GPU info

This is occurs on both an L4 and an A100 setup on a stock GCP machine.

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA L4           On   | 00000000:00:03.0 Off |                    0 |
| N/A   42C    P8    16W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA L4           On   | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    17W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

In terms of the length of the arguments to the calculate_x_pure method I tried a couple of options with different model sizes (32 and 27 latents):

With latents 32 long, max batch size was 31
With latents 27 long, max batch size was 33

**Comment by samskiter** [comment]
Update:

Have tried with CUDA 12.3 and appropriate JAX/Jaxlib and the problem seems to resolve. I don't know whether to leave this open but I think I've resolved the issue :)

**Comment by hawkinsp** [comment]
I strongly suspect that we found an incorrect ptxas version (perhaps from CUDA 11.8) in your PATH, and updating your CUDA installation fixed it.

I suspect https://github.com/openxla/xla/pull/7884, which landed recently, would have fixed the issue also.
