### ISSUE TITLE
Pallas Tutorial outputs RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by bsaoptima** [google/jax#20008]
### Description

Hi there,

I am trying to learn Pallas by running the code bits from the official documentation from Jax but I am having trouble understanding why I'm short on GPU memory.

```
from functools import partial
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp
import numpy as np

def matmul_kernel(x_ref, y_ref, z_ref):
  z_ref[...] = x_ref[...] @ y_ref[...]

def matmul(x: jax.Array, y: jax.Array):
  return pl.pallas_call(
    matmul_kernel,
    out_shape=jax.ShapeDtypeStruct((x.shape[0], y.shape[1]), x.dtype),
    grid=(2, 2),
    in_specs=[
      pl.BlockSpec(lambda i, j: (i, 0), (x.shape[0] // 2, x.shape[1])),
      pl.BlockSpec(lambda i, j: (0, j), (y.shape[0], y.shape[1] // 2))
    ],
    out_specs=pl.BlockSpec(
      lambda i, j: (i, j), (x.shape[0] // 2, y.shape[1] // 2)
    )
  )(x, y)
k1, k2 = jax.random.split(jax.random.PRNGKey(43))
x = jax.random.normal(k1, (1024, 1024))
y = jax.random.normal(k2, (1024, 1024))
z = matmul(x, y)
np.testing.assert_allclose(z, x @ y) 
```

This code which is copy pasted from the documentation (except for the PRNGKey) is giving me the following error:

`XlaRuntimeError: RESOURCE_EXHAUSTED: Shared memory size limit exceeded: requested 4194304, available: 101376`

I saw that to manage memory allocation, we can set 3 environment variables to skip the part where Jax pre-allocates 75% of the memory, but it is still giving me the error.

Any ideas on this? First time really diving into GPUs so I might not have all the theoretical concepts.

### System info (python version, jaxlib version, accelerator, etc.)

jax=0.4.25
jaxlib=0.4.25+cuda11.cudnn86
jaxtyping=0.2.25
python=3.11.8

**Comment by bsaoptima** [comment]
Why did I close the issue? Just realised someone else was on the shared GPU, I ran the code with smaller matrices and it works fine.
