### ISSUE TITLE
[v0.4.26] Fails to initialize CUDA backend after jax_cuda_visible_devices is set

### ISSUE THREAD

**Issue by wukefe** [google/jax#20722]
### Description

In version 0.4.26:
```
>>> import jax
>>> jax.config.update("jax_cuda_visible_devices", "0")
>>> jax.devices()
CUDA backend failed to initialize: jaxlib/cuda/versions_helpers.cc:90: operation gpuDeviceGetAttribute( &major, GPU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, device) failed: CUDA_ERROR_NOT_INITIALIZED (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[CpuDevice(id=0)]
```

But it works in version 0.4.23:
```
>>> import jax
>>> jax.config.update("jax_cuda_visible_devices", "0")
>>> jax.devices()
[cuda(id=0)]
```

### System info (python version, jaxlib version, accelerator, etc.)

A DGX V100 machine

Version 0.4.26
```
jax                          0.4.26
jaxlib                       0.4.26+cuda12.cudnn89
```

Version 0.4.23
```
jax                          0.4.23
jaxlib                       0.4.23+cuda12.cudnn89
```

**Comment by wukefe** [comment]
I figured it out!  It is due to incorrect jax version.  I need to install jax with cuda12 support.  Reinstalling jax as follows that fixes the issue.

```
pip install jax[cuda12]==0.4.26 jaxlib==0.4.26+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
