### ISSUE TITLE
CUDA_ERROR_INVALID_HANDLE when multiple GPUs are present and TF is also in use.

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#2742]
> @mktal can you share the exact error you're getting, and also the code that's producing it? That's odd you'd see this with two identical GPUs.

The following error was produced using the trax master branch, jax 0.1.57 and jaxlib 0.1.37. My gpu configurations are

```
$ nvidia-smi
Thu Jan 30 06:03:14 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:02:00.0 Off |                    0 |
| N/A   33C    P0    49W / 250W |  22764MiB / 22919MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:03:00.0 Off |                    0 |
| N/A   35C    P0    51W / 250W |  20756MiB / 22919MiB |     29%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:83:00.0 Off |                    0 |
| N/A   34C    P0    53W / 250W |    619MiB / 22919MiB |     27%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:84:00.0 Off |                    0 |
| N/A   36C    P0    50W / 250W |    619MiB / 22919MiB |     29%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

```
$ python trax/trainer.py --config_file=./trax/configs/mlp_mnist.gin

I0130 05:57:38.439771 140589291689728 trainer_lib.py:752] No --output_dir specified
No --output_dir specified
I0130 05:57:38.440040 140589291689728 trainer_lib.py:752] Using default output_dir: /nfs/private/trax/MLP_mnist_20200130_0557
Using default output_dir: /nfs/private/trax/MLP_mnist_20200130_0557
I0130 05:57:39.167536 140589291689728 inputs.py:141] No dataset directory provided. Downloading and generating dataset for mnist inside data directory /nfs/private/tensorflow_datasets/ For large datasets it is better to prepare datasets manually!
I0130 05:57:39.211611 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.219218 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.233974 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.251142 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.253719 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.253939 140589291689728 dataset_builder.py:434] Constructing tf.data.Dataset for split train, from /nfs/private/tensorflow_datasets/mnist/1.0.0
I0130 05:57:39.521964 140589291689728 dataset_builder.py:193] Overwrite dataset info from restored data version.
I0130 05:57:39.526323 140589291689728 dataset_builder.py:273] Reusing dataset mnist (/nfs/private/tensorflow_datasets/mnist/1.0.0)
I0130 05:57:39.526546 140589291689728 dataset_builder.py:434] Constructing tf.data.Dataset for split test, from /nfs/private/tensorflow_datasets/mnist/1.0.0
I0130 05:57:39.994026 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
I0130 05:57:40.006169 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
I0130 05:57:40.013097 140589291689728 inputs.py:443] Heuristically setting bucketing to False based on shapes of target tensors.
2020-01-30 05:57:44.782346: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.782757: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783067: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783398: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783678: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.783957: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.784232: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_INVALID_HANDLE: invalid resource handle; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-30 05:57:44.954529: E external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:758] Execution of replica 0 failed: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
Traceback (most recent call last):
  File "trax/trainer.py", line 171, in <module>
    app.run(main)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "trax/trainer.py", line 164, in main
    trainer_lib.train(output_dir=output_dir)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/nfs/private/play/trax/trax/supervised/trainer_lib.py", line 632, in train
    metrics=metrics, id_to_mask=id_to_mask)
  File "/nfs/private/play/trax/trax/supervised/trainer_lib.py", line 111, in __init__
    rng, init_rng = jax_random.split(rng)
  File "/nfs/private/play/trax/trax/math/backend.py", line 123, in split
    return backend()['random_split'](prng, num)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/random.py", line 244, in split
    return _split(key, num)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/core.py", line 602, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/interpreters/xla.py", line 444, in _xla_call_impl
    return compiled_fun(*args)
  File "/usr/local/miniconda3/envs/trax-dev/lib/python3.6/site-packages/jax/interpreters/xla.py", line 549, in _execute_compiled
    out_bufs = compiled.Execute(input_bufs).destructure()
RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
  In call to configurable 'train' (<function train at 0x7fdd6c847a60>)
```

_Originally posted by @mktal in https://github.com/google/jax/issues/1325#issuecomment-579981180_

(The original issue in #1325 was fixed, so I'm forking this into a new issue.)

The problem seems to require:
a) multiple GPUs,
b) using both JAX and TF in the same process.

**Comment by david-waterworth** [comment]
I'm seeing a similar stack trace using FLAX with 2 x 1080Ti's, I'm using tf.Data to create a pipeline for a FLAX model. I don't have a problem with JAX, tensorflow and catboost train fine on my GPU's.

I'll try and post more details later - I've uninstalled JAX GPU support for now so I could get some work done.

**Comment by hawkinsp** [comment]
I have a strong suspicion this issue is fixed at head; we fixed an issue related to accidental sharing of GPU contexts in the same process some months ago. Unfortunately there's not enough detail here for me to reproduce the issue and check.

Closing, on the assumption that this issue is fixed. Please reopen with instructions to reproduce it if you still experience it!
