### ISSUE TITLE
Set device id programmatically

### ISSUE THREAD

**Issue by choltz95** [google/jax#2965]
Hi, couldn't see if this has already been asked - is there an xla api for setting the device id for compilation & run? I have tried setting visible devices, but I still see all available GPUs being exposed, and Jax defaults to id 0 where another Jax process is running & has already preallocated memory. I want to run multiple trials in parallel on separate GPUs.

```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="1"  # specify which GPU(s) to be used

from jax.lib import xla_bridge
print(xla_bridge.get_backend().devices())
>>[GpuDevice(id=0), GpuDevice(id=1), GpuDevice(id=2), GpuDevice(id=3)]
...
out_shape, net_params = net_init(rng, in_shape)
>>RuntimeError: CUDA operation failed: out of memory
```

Is there a way to do this or a different workaround?

**Comment by skye** [comment]
Please see https://jax.readthedocs.io/en/latest/faq.html#controlling-data-and-computation-placement-on-devices. Does this do what you want?

**Comment by choltz95** [comment]
Right - must have missed that. Thanks!

**Comment by YiningWang2** [comment]
Hello, After reading these related issues, I have not got an effective way, can you share me how you solved your problems?

> Right - must have missed that. Thanks!

Hello, After reading these related issues, I have not got an effective way, can you share me how you solved your problems?

**Comment by khasmamad99** [comment]
@choltz95, could you, please, elaborate on how you solved the issue?
I tried
```
jax.default_device = jax.devices('gpu')[gpu_num]
```
and set `gpu_num` differently, but it did not work. I am getting:
```
RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error
```
The versions I am using are:
```
$ pip list | grep jax
jax                        0.2.25
...
jaxlib                     0.1.73+cuda11.cudnn82
...
```

**Comment by khasmamad99** [comment]
When I look at `nvidia-smi`, I see that the same Python process is running on all the devices:
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2885      G   /usr/lib/xorg/Xorg                 28MiB |
|    0   N/A  N/A      8747      C   python                          10257MiB |
|    0   N/A  N/A     10949      G   /usr/bin/gnome-shell                8MiB |
|    1   N/A  N/A      8747      C   python                            153MiB |
|    2   N/A  N/A      8747      C   python                            153MiB |
|    3   N/A  N/A      8747      C   python                            153MiB |
+-----------------------------------------------------------------------------+
```

**Comment by khasmamad99** [comment]
The issue is solved after I do
```
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = gpu_id
```
at the beginning of the script (i.e., before any `jax` or `jax`-related imports).
