### ISSUE TITLE
Jitting and memory leaks

### ISSUE THREAD

**Issue by xwinxu** [google/jax#3158]
I am using a computing cluster to run my jobs. I notice that Slurm keeps killing my jobs within seconds of submission due to out of memory errors, which I believe is because JAX is asking for more memory than allocated since GPU usage seems to increase, potentially due to a memory leak. I am running `cuda10.1`.

This is the stack trace I get:
```
RuntimeError: Internal: Unable to launch cuBLAS gemm on stream 0x562d67df53e0
2020-05-18 19:33:00.557492: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:940] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
        _PyDict_DelItem_KnownHash
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallDict
        PyObject_CallFunctionObjArgs
        PyObject_ClearWeakRefs
        PyDict_SetItem
        PyDict_SetItemString
        PyImport_Cleanup
        Py_FinalizeEx
        _Py_UnixMain
        __libc_start_main
*** End stack trace ***
2020-05-18 19:33:00.557560: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:88] Check failed: pair.first->SynchronizeAllActivity() 
slurmstepd: error: *** JOB 505887 ON gpu117 CANCELLED AT 2020-05-18T19:33:01 ***
```
I also get this sometimes as in this [issue](https://github.com/google/jax/issues/1491):
```
 File "...py", line 126, in apply_fun
    outputs = sdeint(augmented_drift, augmented_diffusion, aug_init(inputs), np.linspace(0, 1, 100), rng)
  File "...py", line 49, in sdeint
    _, states = lax.scan(f_scan, dict(curr_state=s_init), xs)
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 955, in scan
    linear=(False,) * (len(consts) + len(in_flat)))
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 1337, in scan_bind
    num_carry=num_carry, linear=linear)
  File ".../anaconda/lib/python3.7/site-packages/jax/core.py", line 214, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "...anaconda/lib/python3.7/site-packages/jax/interpreters/batching.py", line 134, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 1278, in _scan_batching_rule
    num_consts=num_consts, num_carry=num_carry, linear=linear)
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 1337, in scan_bind
    num_carry=num_carry, linear=linear)
  File "...anaconda/lib/python3.7/site-packages/jax/core.py", line 211, in bind
    return self.impl(*args, **kwargs)
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 981, in _scan_impl
    _, *outs = while_loop(cond_fun, body_fun, init_val)
  File "...anaconda/lib/python3.7/site-packages/jax/lax/lax_control_flow.py", line 246, in while_loop
    body_nconsts=len(body_consts), body_jaxpr=body_jaxpr)
  File "...anaconda/lib/python3.7/site-packages/jax/core.py", line 211, in bind
    return self.impl(*args, **kwargs)
  File ".../anaconda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 218, in apply_primitive
    return compiled_fun(*args)
  File "...anaconda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 315, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Resource exhausted: Out of memory while trying to allocate 208652400 bytes.
```

I'm wondering where the inefficiencies are in my code if this may be the issue. I have one `jit` in my `update` function which calls `value_and_grad` and updates the optimizer (Adam). And I use `lax.scan` to replace my for loops which are called when making a prediction. The `update` function is most top level so I have no jitted anything else. I've also tried calling `xla._xla_callable.cache_clear()` (from this [issue](https://github.com/google/jax/issues/2072)) to no avail. This error happens quite inconsistently across my jobs and I'd appreciate any guidance in investigating the issue.

Thanks for your time!

**Comment by mattjj** [comment]
@skye can you take a look?

@xwinxu have you seen the [GPU memory allocation](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html) note?

**Comment by mattjj** [comment]
Unfortunately, unless this is something @skye happens to have seen before (or if she has some great guesses as to what's going on), it might be hard to debug this without some kind of repro. @xwinxu any chance you can try to generate a minimal repro of this?

**Comment by xwinxu** [comment]
Ah I have not seen the GPU memory allocation note, thanks for linking! The issue might fall into the _Running Multiple Jax Processes Concurrently_ issue, I will try setting `XLA_PYTHON_CLIENT_PREALLOCATE=false` since I'm shooting off many runs with some potentially occupying the same node (depending on what the scheduler decides). I'm definitely allocating more than enough memory for the task I'm running though, so I presume it's some poor timing with how I shoot off my jobs. 

Unfortunately I cannot find a reliable way of reproducing this, it kind of happens based on luck but especially when multiple things are running concurrently!

**Comment by mattjj** [comment]
Fingers crossed that that works!

I think `XLA_PYTHON_CLIENT_PREALLOCATE=false` might be slow though, and can lead to fragmentation which can cause its own OOMs. How about `XLA_PYTHON_CLIENT_MEM_FRACTION=.2` or some fraction based on the number of simultaneous JAX processes you might be running?

**Comment by xwinxu** [comment]
I tried those variables, and it still seems to be giving me those errors. I wish I could just show you my code, it's quite a long example with many moving parts though so let me think if I could come up with some minimum repro - will update here.

**Comment by xwinxu** [comment]
I think the issue is in `lax.scan` as that's the major change in my code since noticing this OOM error. Is there any insight into how `scan` interacts with `jit`ing and gpu processes?

**Comment by skye** [comment]
That first stack is quite troubling! I'm guessing this can happen in low-memory conditions, but it's not a very friendly error message... if we resolve the OOM issue, this error will probably go away too.

Did you switch to scan from a regular Python loop? That may have resulted in more memory being used, since it's presumably working with larger arrays. From your stack trace, it looks like the scan isn't running under a jit. If you can, it might help to jit

**Comment by skye** [comment]
I somehow clicked close and comment while I was typing :)

**Comment by xwinxu** [comment]
Yep, I switched a python for loop to a `scan`. That's odd, I jitted the function that calls this function, but I can try jitting this function itself as well to force the loop to run under a jit. 

Below is a function that I suspect may be causing the issue, I think I suspect it because of the `PyDict` in the first stack trace above.  The loop runs for 100 iterations in my code. 
Do you see anything obviously wrong/unsafe with it?
```
@partial(jit, static_argnums=(0, 1, 3))
def sdeint(f, g, s_init, ts, rng):
  rngs = jax.random.split(rng, len(ts) - 1)

  def f_scan(carry, x):
    t0, t1, rng = x[0], x[1], x[2:].astype('uint32')
    curr_state = carry['curr_state']
    h = t1 - t0
    f_out = f(t0, curr_state)
    g_out = g(t0, curr_state)
    eps = random.normal(rng, s_init.shape)
    dif = np.sqrt(h) * eps * g_out
    curr_state = curr_state + h * f_out + dif
    carry['curr_state'] = curr_state
    return carry, curr_state
  xs = np.concatenate([ts[:-1][..., np.newaxis], ts[1:][..., np.newaxis], rngs], axis=-1)
  _, states = lax.scan(f_scan, dict(curr_state=s_init), xs)

  return states
```

Changing it to this is fine (but runs super slowly, as I notice jitting a python for loop is even slower):
```
def sdeint(f, g, s_init, ts, rng):
  rngs = jax.random.split(rng, len(ts) - 1)
  curr_state = s_init
  states = []
  for t0, t1, rng in zip(ts[:-1], ts[1:], rngs):
    h = t1 - t0
    f_out = f(t0, curr_state)
    g_out = g(t0, curr_state)
    eps = random.normal(rng, s_init.shape)
    diffusion = np.sqrt(h) * eps * g_out
    curr_state = curr_state + h * f_out + diffusion
    states.append(curr_state)
  return states
```

**Comment by jekbradbury** [comment]
Using `XLA_PYTHON_CLIENT_MEM_FRACTION` doesn't put a ceiling on how much memory the process will claim from the GPU (it's closer to a floor; I'm not sure there's a way to provide a ceiling in JAX, although Skye would know). Have you seen this occur even without sharing a GPU between multiple processes?

**Comment by xwinxu** [comment]
Yep, this occurs even when I go into a node and run it interactively. I can try changing to another control flow lax op to see if that could solve the issue.

**Comment by jekbradbury** [comment]
Can you try printing out `object_memory_usage` from https://gist.github.com/levskaya/37f72b76bd5c72f9e5ce48ce154a9246 at a couple different places during the program, to see if allocations are building up?

Also, do you have a reliable+self-contained reproducer in the single-GPU context (even a not at all minimal one?) If you're able to share it with us we can run it with some internal profiling tools and maybe narrow down where the leak is coming from (some amount of those tools are available publicly as well, so that may also be an option).

**Comment by xwinxu** [comment]
Here's the progression I get from printing out the memory usage at the start and end of when I load my data, initialize my model, initialize parameters, initialize my optimizer, start training, and call update - which calls the function with the lax scan I printed above (*): 
```
| device | count | memory  | total   |
|--------|-------|---------|---------|
| gpu0   | 1     | 8       | 8       |
| ''     | 5     | 244     | 244     |
| ''     | 6     | 248     | 248     |
| ''     | 40    | 2608968 | 2608968 |
| ''     | 108   | 7826408 | 7826408 |
| ''     | 109   | 7845880 | 7845880 |
| ''     | ''    | ''      | ''      |
| ''     | 112   | 7845968      | 7845968    |
| ''     | 113   | 7845968 | 7845968 |
| ''     | ''    | ''      | ''      |
| ERROR  | ====  | ======= | ======= |
```

So it seems like the step after initializing my parameters and optimizers increases the usage drastically. I can't create a smaller example to reproduce the issue, but the function I sent above is really the only thing aside from standard procedures listed at (*). I can ask if I'm allowed to share my code, let me get back to you.

**Comment by jekbradbury** [comment]
There's a specific XLA bug having to do with memory buffer assignment in loops that seems especially common with `scan`; the symptom is temporary memory usage during scan execution that's quadratic (rather than linear) in the sequence length. If you can send us the XLA HLO (`XLA_FLAGS="--xla_dump_to=/some/path/"`, then identify the biggest "pre-optimization" and corresponding "post-optimization" text files in that folder), we should be able to figure out if it's triggering that bug.

**Comment by EyalRozenberg1** [comment]
I experience the exact same bug while running on multiple GPUs.
Have we found the reason?

**Comment by EyalRozenberg1** [comment]
Seems like the bug occurs when returning from a function a large np.array. more specifically, I assume that Jax tries to allocate a replica of the returned value in the following function: pxla.execute_replicated(), and dies on its third line - out_bufs = compiled.execute_on_local_devices(list(input_bufs))

**Comment by skye** [comment]
Hey @EyalRozenberg1 , can you open a new issue and provide some more context, like a full stack trace + error message, and a repro if you have one? We were able to track down @xwinxu's issue offline, which turned out to be a `scan` returning a huge array inside a jitted function. It's possible you have a similar issue, but we'll need more information.

**Comment by EyalRozenberg1** [comment]
Sure, I will. I don't think this is my problem here because it occurs in any size of an array.

btw. for other purposes, how did you resolve the 'huge array' issue? is there a way to bypass this problem?

**Comment by skye** [comment]
In this case, the only way to resolve the issue is to change @xwinxu's program, since currently it fundamentally requires a lot of memory (which is the result of returning a pretty big array from a length-100 scan, so the length-100 output array is too big to fit in device memory).
