### ISSUE TITLE
GPU not detected by JAX. Warning: No GPU/TPU found, falling back to CPU.

### ISSUE THREAD

**Issue by 8sukanya8** [google/jax#4059]
JAX library does not use the GPU and shows warning
```
path/venv/lib/python3.6/site-packages/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
```
My code looks somewhat like this. I am not able to post the exact code I was using, as it is a part of an exercise.

```
from trax.fastmath import numpy as fastnp
v1 = np.array([[0.1172474, 0.6472824, 0.8061181],[0.6172836 , 0.5123475, 0.9017283]])
v2 = np.array([[ 0.5933123,  0.1162829,  0.9063872],[-0.6481012 , -0.57543534, -0.7162344]])
margin=0.25
scores = fastnp.dot(v1, v2.T)
```

Also, on checking the backend devices with the following code, I get to see only the CPU.
```
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
```
```
cpu
```

However, if I check devices using tensorflow, I can see the GPU.
```
import tensorflow as tf
tf.config.list_physical_devices('GPU')
```

```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Here are the outputs of nvcc and nvidia-smi.
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

```
Fri Aug 14 11:19:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:31:00.0  On |                  N/A |
|  0%   49C    P8    17W / 175W |    894MiB /  7979MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1562      G   /usr/lib/xorg/Xorg                 24MiB |
|    0   N/A  N/A      1696      G   /usr/bin/gnome-shell               50MiB |
|    0   N/A  N/A      1939      G   /usr/lib/xorg/Xorg                493MiB |
|    0   N/A  N/A      2071      G   /usr/bin/gnome-shell              188MiB |
|    0   N/A  N/A      2984      G   .../debug.log --shared-files       17MiB |
|    0   N/A  N/A      3386      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      4283      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      5579      C   ...ffice/program/soffice.bin       97MiB |
|    0   N/A  N/A      5665      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      5813      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      8409      G   /usr/lib/firefox/firefox            2MiB |
+-----------------------------------------------------------------------------+
```

Can I make JAX use the GPU?

**Comment by 8sukanya8** [comment]
Closing the issue as the problem has been resolved.  It turns out that I had CUDA installed. I also installed CUDNN and then installed JAX with both CPU and GPU support (using existing CUDA and CUDNN libraries) according to the instructions [here](https://github.com/google/jax).
