### ISSUE TITLE
segfault for cuda version mismatch

### ISSUE THREAD

**Issue by ethanabrooks** [google/jax#5301]
To reproduce:
```
❯ python -c 'import jax; jax.random.PRNGKey(0)'
2021-01-01 17:26:40.075619: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2021-01-01 17:26:40.075684: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-01-01 17:26:40.075705: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-01-01 17:26:40.075720: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-11.0
2021-01-01 17:26:40.075734: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-01-01 17:26:40.075748: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-01-01 17:26:40.117991: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:63] Running ptxas --version returned 256
2021-01-01 17:26:40.141506: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:421] ptxas returned an error during compilation of ptx to sass: 'Internal: ptxas exited with non-zero error code 256, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
zsh: abort (core dumped)  python -c 'import jax; jax.random.PRNGKey(0)'
```
Here are all my versions
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
❯ conda list | ag jax
jax                       0.2.7                    pypi_0    pypi
jaxlib                    0.1.57+cuda110           pypi_0    pypi
❯ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
❯ cat /usr/local/cuda-7.5/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      3
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 8
```
The problem was that I had installed `jax` for cuda 11.0 instead of 11.1.

**Comment by zhangqiaorjc** [comment]
Is this still a problem?

**Comment by ethanabrooks** [comment]
My code is working now, but as far as I know, jax still segfaults in these circumstances instead of raising an error.

**Comment by zhangqiaorjc** [comment]
Great that you fixed it!

For future reference, we do have instructions for installing the jaxlib wheel for the correct cuda version

https://github.com/google/jax#installation

The warning messages in your first comment could be a good hint if users believe that they installed a wheel with cuda support but cuda is still not found.

```
2021-01-01 17:26:40.075619: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2021-01-01 17:26:40.075684: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-01-01 17:26:40.075705: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-01-01 17:26:40.075720: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-11.0```

**Comment by hayday100** [comment]
The same segfault occurs on my laptop with RTX 2080 with nvidia-460 driver and CUDA 11.2.  It doesn't matter which version of jaxlib I use.  It occurs to jaxlib==0.1.65+cuda112 or jaxlib==0.1.67+cuda111.  What's interesting is that it works on my server with M60 grid GPU and the same version of nvidia-460 driver and CUDA 11.2 with jaxlib==0.1.65+cuda112.  It is very strange!
