### ISSUE TITLE
Bug when computing Hessian Inverse

### ISSUE THREAD

**Issue by unrealwill** [google/jax#5380]
Hello, I'm trying to compute the matrix inverse of the hessian.
It doesn't seem to be related to the hessian specifically because it also doesn't work when composing with a single grad.

```
from jax import vmap
from jax import grad,jit
import jax.numpy as jnp
import numpy as np
import jax


def jaxbug():
    def L( x ):
        return jnp.sum(x*x)

    def Hessian( x ):
        M = jax.hessian(L,0)(x)
        return M

    def HessianInverse( x ):
        M = jax.hessian(L,0)(x)
        invM = jnp.linalg.inv(M)
        #works in simple cases  replace above with
        #invM = np.linalg.inv(M)
        return invM

    X = 3.0*np.ones((2),dtype="float32")

    print("Hessian")
    print(Hessian(X))

    print("Hessian Inverse")
    print( HessianInverse(X) )


def jaxbug2():
    def L( x ):
        return jnp.sum(x*x)

    def grad( x ):
        M = jax.grad(L,0)(x)
        return M

    def gradInverse( x ):
        M = jax.grad(L,0)(x)
        invM = jnp.linalg.inv(M)
        #works in simple cases replace above with
        #invM = np.linalg.inv(M)
        return invM

    X = 3.0*np.eye((2),dtype="float32")

    print(" grad")
    print(grad(X))

    print(" grad Inverse")
    print( gradInverse(X) )

#jaxbug()
jaxbug2()
```

The above code crash with the following error stack : 

```
python3 jaxbug.py 
 grad
[[6. 0.]
 [0. 6.]]
 grad Inverse
2021-01-12 22:05:33.201453: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-01-12 22:05:33.201497: W external/org_tensorflow/tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
2021-01-12 22:05:33.201538: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1809] Execution of replica 0 failed: Internal: Unable to launch triangular solve for thunk 0x133a1330
Traceback (most recent call last):
  File "jaxbug.py", line 56, in <module>
    jaxbug2()
  File "jaxbug.py", line 53, in jaxbug2
    print( gradInverse(X) )
  File "jaxbug.py", line 42, in gradInverse
    invM = jnp.linalg.inv(M)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/_src/numpy/linalg.py", line 336, in inv
    a, lax.broadcast(jnp.eye(a.shape[-1], dtype=lax.dtype(a)), a.shape[:-2]))
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/api.py", line 371, in f_jitted
    return cpp_jitted_f(*args, **kwargs)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/api.py", line 284, in cache_miss
    donated_invars=donated_invars)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1229, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1220, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1232, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 598, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/interpreters/xla.py", line 572, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/interpreters/xla.py", line 830, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Unable to launch triangular solve for thunk 0x133a1330
2021-01-12 22:05:33.259843: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/local_device_state.cc:68] Error when closing device: Internal: stream did not block host until done; was already in an error state
2021-01-12 22:05:33.260070: W external/org_tensorflow/tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
```

**Comment by zhangqiaorjc** [comment]
`2021-01-12 22:05:33.201453: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
`

It would seem that you didn't install jaxlib GPU version

Could you follow the installation guide to install jaxlib GPU support?
https://github.com/google/jax#installation

**Comment by hawkinsp** [comment]
I'm actually guessing this is the GPU wheel, but for some reason the GPU support failed to initialize. Can you try running with the environment variable `TF_CPP_MIN_LOG_LEVEL=0` set and share the logs?

**Comment by unrealwill** [comment]
Thanks,

I am indeed using the GPU wheel,  
It seems there is some problem initializing the cublas library even though it was opened successfully : 
```
2021-01-12 22:46:56.292552: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-12 22:46:56.428850: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED

```

I'll try tomorrow to redo a fresh cuda install / jax / tensorflow.

Full log :

```
TF_CPP_MIN_LOG_LEVEL=0 python3 jax
jaxbug.py  jaxlag.py  
(venvtf2.4)  TF_CPP_MIN_LOG_LEVEL=0 python3 jaxbug.py 
2021-01-12 22:46:54.122286: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-12 22:46:54.183076: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-12 22:46:54.442500: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2b45390 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2021-01-12 22:46:54.442544: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Interpreter, <undefined>
2021-01-12 22:46:54.459841: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2593835000 Hz
2021-01-12 22:46:54.460353: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ae4160 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-12 22:46:54.460373: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-12 22:46:54.461884: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-12 22:46:54.499487: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-12 22:46:54.499900: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x284a150 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-12 22:46:54.499919: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
2021-01-12 22:46:54.500235: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/nvidia_gpu_device.cc:119] XLA backend allocating 1802620108 bytes on device 0 for BFCAllocator.
2021-01-12 22:46:54.500368: I external/org_tensorflow/tensorflow/stream_executor/tpu/tpu_platform_interface.cc:74] No TPU platform found.
Hessian
[[2. 0.]
 [0. 2.]]
inv Hessian
2021-01-12 22:46:55.455978: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-01-12 22:46:55.924679: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-12 22:46:56.292552: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-12 22:46:56.428850: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-01-12 22:46:56.428895: W external/org_tensorflow/tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
2021-01-12 22:46:56.428929: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1809] Execution of replica 0 failed: Internal: Unable to launch triangular solve for thunk 0x143463e0
Traceback (most recent call last):
  File "jaxbug.py", line 58, in <module>
    jaxbug()
  File "jaxbug.py", line 29, in jaxbug
    print(jnp.linalg.inv(h))
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/_src/numpy/linalg.py", line 336, in inv
    a, lax.broadcast(jnp.eye(a.shape[-1], dtype=lax.dtype(a)), a.shape[:-2]))
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/api.py", line 371, in f_jitted
    return cpp_jitted_f(*args, **kwargs)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/api.py", line 284, in cache_miss
    donated_invars=donated_invars)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1229, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1220, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 1232, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 598, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/interpreters/xla.py", line 572, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/interpreters/xla.py", line 830, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Unable to launch triangular solve for thunk 0x143463e0
2021-01-12 22:46:56.484537: I external/org_tensorflow/tensorflow/stream_executor/stream.cc:4977] [stream=0x2c5dcd0,impl=0x2a3b600] Internal: stream did not block host until done; was already in an error state
2021-01-12 22:46:56.484629: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/local_device_state.cc:68] Error when closing device: Internal: stream did not block host until done; was already in an error state
2021-01-12 22:46:56.484847: I external/org_tensorflow/tensorflow/stream_executor/stream.cc:4977] [stream=0x2c5dcd0,impl=0x2a3b600] Internal: stream did not block host until done; was already in an error state
2021-01-12 22:46:56.484858: W external/org_tensorflow/tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state

```

**Comment by unrealwill** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

My nvidia driver are up-to-date : 

```
 nvidia-smi
Tue Jan 12 23:39:27 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     
```
I cannot easily pin this version number to a previous version but CUDA drivers are backwards compatible

I reinstalled the specific cuda version you specify in the installation (aka cuda 11-0)
```
sudo apt-get install cuda-11-0
virtualenv -p python3 venvjax
source ~/venvjax/bin/activate
pip install --upgrade pip
pip install --upgrade jax jaxlib==0.1.57+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
TF_CPP_MIN_LOG_LEVEL=0 python3 jaxbug.py 
```

It doesn't work. Same errors, except it's now loading 11.0 library instead of 11.1.
I also tried with cuda-10-1 and it doesn't work.

Can you please advise ?

Thank you

**Comment by unrealwill** [comment]
I tried my code with the cpu version and it works.
I also tried with the gpu version on a  GeForce GTX 1080 Ti, Compute Capability 6.1 and it works.

So the problem for me is only occurring on my laptop with GeForce GTX 960M, Compute Capability 5.0 

Don't waste anymore time, I'll close the bug as it's probably just an incompatible device issue, I'll work around it by using cpu and my other machine. Feel free to reopen if you want.
Thanks.

**Comment by hawkinsp** [comment]
I have one other guess: can you show the complete `nvidia-smi` output? Is the GPU low on RAM?

As an experiment, can you try `XLA_PYTHON_CLIENT_PREALLOCATE=false` (see https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html ) ?

I've seen cuBlas fail to initialize when it runs out of RAM, and it doesn't always give the best error message when that happens.

**Comment by unrealwill** [comment]
@hawkinsp Nice guess +1: 

It runs fine on GPU when I use XLA_PYTHON_CLIENT_PREALLOCATE=false

Thanks very much

When I don't use it : 
Full log nvidia-smi output, captured at the instant before the crash.
**+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   61C    P0    N/A /  N/A |   1816MiB /  2004MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1996      G   /usr/lib/xorg/Xorg                 72MiB |
|    0   N/A  N/A      6114      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     20201      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     25428      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     32561      C   python3                          1734MiB**

**Comment by hawkinsp** [comment]
Awesome! We're planning to make `XLA_PYTHON_CLIENT_PREALLOCATE=false` the default some time soon, which should fix the problem once and for all.

**Comment by JakobThumm** [comment]
I had the issue that GPU support was dropped if I selected `XLA_PYTHON_CLIENT_PREALLOCATE=false` or `XLA_PYTHON_CLIENT_PREALLOCATE=platform`. Thankfully, `XLA_PYTHON_CLIENT_MEM_FRACTION=.80` worked. https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html  is an excellent resource if you are struggling with similar problems.
