### ISSUE TITLE
Could not load dynamic library 'libcudnn.so.8'

### ISSUE THREAD

**Issue by ybj14** [google/jax#5464]
I'm working on GeForce GTX 1080 Ti, cuda 11.0, cudnn7, but when training jax keeps telling me `Could not load dynamic library 'libcudnn.so.8'`.

My environment variable is 
```bash
$ echo $LD_LIBRARY_PATH
/opt/cudnn/lib64:/usr/local/cuda//lib64:/opt/cudnn/lib64:/usr/local/cuda/lib64
$ ls /opt/cudnn/lib64/ 
libcudnn.so  libcudnn.so.7  libcudnn.so.7.6.0  libcudnn_static.a
``` 

Jax is installed successfully with ` pip install --upgrade jax jaxlib==0.1.55+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html` and
```python
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
```
outputs gpu.

But when training model, jax tells me
```
2021-01-19 21:40:57.616373: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/cudnn/lib64:/usr/local/cuda//lib64:/opt/cudnn/lib64:/usr/local/cuda/lib64
2021-01-19 21:40:57.616390: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```
I wonder how does jax decide which version of cudnn to use? Seems that I've only got cudnn7 but jax requires cudnn8.

**Comment by hawkinsp** [comment]
That's correct. The CUDA 11 versions of JAX are built against CuDNN 8. We should probably document this at the least. Can you install CuDNN 8?

**Comment by ybj14** [comment]
Unfortunately, I do not have the permission to sudo install CuDNN 8 in the server I work on. I have tried to use lower versions of jax and jaxlib and cuda (like `jax0.2.0+jaxlib0.1.42+cuda10.0`). But I'm still getting this error.

**Comment by hawkinsp** [comment]
I think your best bet for the moment is to:
a) ask your system administrator to install CuDNN 8, or
b) use a CUDA 10.2 wheel, if CUDA 10.2 is installed.
c) build `jaxlib` from source with CUDA 11 and CuDNN 7.

We don't release a wheel with the particular combination you need at the moment. Maybe we could in the future, although my personal temptation would be to drop completely CuDNN 7 support at some point.

**Comment by ybj14** [comment]
Thanks for replying. I have solved my problem by installing CuDNN 8 under my local directory. But I think it will be of great help if CuDNN dependencies could be made more explicit in the doc.
