### ISSUE TITLE
Improve XLA:GPU NCCL support

### ISSUE THREAD

**Issue by jekbradbury** [google/jax#606]
JAX's approach to parallelism is to piggyback on the XLA runtime's support for replicated computation. Recently, @cdleary added support for NCCL-based AllReduce to that infrastructure, but there are a few more things that need to happen before JAX can be performance-competitive for multi-GPU training.

From @skye:

> `NcclAllReduceThunk` currently [calls `ncclCommInitAll`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc#L270) for every `AllReduce`.
> 
> This is a big performance bottleneck for JAX, because `ncclCommInitAll` does a bunch of synchronous GPU memory allocations which take way longer than the actual collective operation itself. TensorFlow gets around this by [caching the returned communicators](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/nccl/nccl_manager.cc#L195) for a given set of participants. Ideally the XLA runtime would do something similar (possibly by reusing `NcclManager` from TF?).

From @hawkinsp:

> [It] might be preferable if NCCL accepted a user-provided allocator instead.

CC @ngimel @mruberry

**Comment by nottombrown** [comment]
Performant NCCL primitives are also crucial for my workload. 

I'd like to profile how performant things are currently. Is there an example of how to call out to NCCL using JAX?

**Comment by mattjj** [comment]
Yes, though we haven't documented it because it's not ready for use due to performance issues.

The [SPMD MNIST example](https://github.com/google/jax/blob/master/examples/spmd_mnist_classifier_fromscratch.py) shows how to use `pmap` together with the `psum` collective. The former builds and executes a replicated computation on multiple accelerators, and the latter gets lowered into a NCCL allreduce-sum on GPU. (You can also nest those to set up parallel meshes, and everything is composable so you can differentiate on the inside or outside.)

On GPU there are two big known performance bugs though. The first is #417, and the second is this issue #606. I suspect #417 compounds #606, which probably means multi-GPU `pmap`s involving `psum` calls are too slow to be useful right now. (Also on GPU `pmap`s can't be nested yet because XLA:GPU doesn't yet have an AllToAll implementation, though we could work around that on our end.)

[The trax library uses `pmap`](https://github.com/tensorflow/tensor2tensor/blob/e56072d9cf2f2fc97399208c5116372cb4a425af/tensor2tensor/trax/trax.py#L280-L290) to write SPMD code as well. We're currently using the trax examples to optimize performance on internal TPUs, and performance GPUs and Cloud TPUs is the next step.

Fortunately these two performance issues seem to explain most or all of the slowness we see in profiles, and they seem surmountable!

**Comment by nottombrown** [comment]
Thanks for the response @mattjj! Glad that you've tracked down the issues.

I did a small bit of profiling, and I'm seeing `~1.4s` of time to allreduce a 4 MB object. This is about 1000x slower than what I get from horovod/pytorch. Am I doing something wrong, or is this the slowdown that we would expect from the two bugs together?

```python
import itertools

import jax.numpy as np
import numpy.random as npr
from jax import pmap, lax, partial
from tqdm import tqdm


@partial(pmap, axis_name='i')
def do_allreduce(x):
    x_full = lax.psum(x, 'i')
    return np.mean(x_full)


if __name__ == '__main__':

    for i in tqdm(itertools.count()):
        x = npr.randn(8, 1, 1024, 1024)  # 4 MB object
        val = do_allreduce(x)
```

**Comment by jekbradbury** [comment]
I think there are some additional slowdowns in that example beyond the two bugs (really missing features) flagged—for instance, you’re also counting host-device latency since you’re starting with a NumPy array, and XLA runtime startup overhead since each allreduce is a separate XLA computation. But even with that a second seems too long, and definitely worth profiling more. The standard I think you should (eventually) hold us to is that fully jitted JAX code should match or beat the performance of any other implementation.

**Comment by mattjj** [comment]
As @jekbradbury pointed out, you might want to run a test that avoids the device transfer on each execution, for example by replacing the `x = ` line with something like this outside the loop:

```python
x = pmap(lambda x: x)(npr.randn(8, 1, 1024, 1024))
```

If you look at `type(x)` you'll see that it's a `ShardedDeviceArray` instance (we should make the repr reflect that too).

**Comment by hawkinsp** [comment]
I think this issue is fixed! XLA now caches the NCCL contexts and multi GPU all-reduce training is looking much more performant. Please try it out!

I'm sure there's more to improve here, but let's open new issues as they come up.
