### ISSUE TITLE
jax.jit silently produces wrong results when using more than 100 DeviceArrays with TPUs on Google Colab

### ISSUE THREAD

**Issue by houeland** [google/jax#6558]
See https://colab.research.google.com/drive/1pCGr4KMX155z5WkjIKIfTbaPrcUTbJeY?usp=sharing to reproduce.

Calling jax.jit with more than 100 DeviceArrays silently fails, and appears to read ~random memory:
```python
print("Devices:", [d.device_kind for d in jax.devices()])
for num_times in [5,99,100,101,102,1000]:
  @jax.jit
  def fn(params):
    sum = 0.0
    for k,v in params.items(): sum += v
    return sum
  params = {'w%d'%i:1.0 for i in range(num_times)}
  output = fn(params)
  print(f"num_times={num_times} output={output}")
```
```
Devices: ['Cloud TPU', 'Cloud TPU', 'Cloud TPU', 'Cloud TPU', 'Cloud TPU', 'Cloud TPU', 'Cloud TPU', 'Cloud TPU']
num_times=5 output=5.0
num_times=99 output=99.0
num_times=100 output=100.0
num_times=101 output=0.0
num_times=102 output=0.0
num_times=1000 output=0.0
```

When running on GPU or CPU, the same code works fine:
```
Devices: ['Tesla T4']
num_times=5 output=5.0
num_times=99 output=99.0
num_times=100 output=100.0
num_times=101 output=101.0
num_times=102 output=102.0
num_times=1000 output=1000.0
```
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Devices: ['cpu']
num_times=5 output=5.0
num_times=99 output=99.0
num_times=100 output=100.0
num_times=101 output=101.0
num_times=102 output=102.0
num_times=1000 output=1000.0
```

FYI:

This might be related to https://github.com/google/jax/issues/5355 although the way it's triggered there is different. I believe there it was passing 37 DeviceArrays at least on the initial call to value_and_grad, both when it works with HIDDEN_SIZE=1 and when it fails with HIDDEN_SIZE=3.

https://github.com/google/flax/issues/769#issuecomment-755391196 mentions "a silent TPU OOM bug that isn't captured correctly", which seems likely to be the case here. (Though not exactly OOM, but out of some resource associated with DeviceArrays. E.g. failing to transfer the data, but running the code anyway.)

What I originally wanted was to use hk.nets.ResNet18, which I believe ended up with 62+62+125 DeviceArrays for the model_params, model_state, and optimizer_state. AFAICT the sum among passed parameters is what matters, so it fails even without the optimizer: https://colab.research.google.com/drive/1tv3QQ03slQ0cLzzLI4I5OlxPQqwMnMTD?usp=sharing

**Comment by hawkinsp** [comment]
I suspect the cutoff at 100 is because above 100 arrays JAX switches to passing parameters as a tuple internally.

**Comment by skye** [comment]
Thanks for reporting this. I found the bug and have a fix in the works, will keep this thread updated. It'll require a new jaxlib release so it might be a few days or more.

If you're blocked on this, a workaround in the meantime is to use a single-device pmap instead of jit (silly, but it should work!).

**Comment by skye** [comment]
FYI https://github.com/tensorflow/tensorflow/commit/6fe59a2c4e201054ec795f77257ed10e781c69a0 should fix this. We'll need to release a new jaxlib in order to access this from colab though.

**Comment by houeland** [comment]
Great, thanks for fixing so quickly!

**Comment by skye** [comment]
You may have thanked me too soon :) But we just released jaxlib 0.1.66 which includes this fix! We'll eventually update Colab to use this version by default, but for now, you can manually install it at the top of your Colab with:
```
!pip install --upgrade jaxlib
```

Also one small thing I noticed about your Colab -- you can replace the preamble setting the TPU env vars with the following snippet now:
```python
from jax.tools import colab_tpu
colab_tpu.setup_tpu()
```
