### ISSUE TITLE
Seemingly random CUDA_ERROR_ILLEGAL_ADDRESS is thrown after correct execution

### ISSUE THREAD

**Issue by Baschdl** [google/jax#6921]
I get a reproducable `CUDA_ERROR_ILLEGAL_ADDRESS` in code which works for the first two executions (see lines above first stack trace) and then errors. It also happens in different functions when code is changed (see second stack trace). 
Running `np.linalg.eigh(jax.random.uniform(key=jax.random.PRNGKey(42), shape=(30, 30)))` (from the second stack trace) in isolation works fine.
I'm not sure which change caused this behavior as it worked before. It also happens on different GPUs. Running it only on the CPU works fine.

I'm open for any pointers how I could debug this further as this is probable not enough information to draw any conclusions at all.

jax version 0.2.13, jaxlib 0.1.67+cuda110

```
Loss reduction: 0.034373939037323
Loss reduction: 0.0363161563873291
2021-06-08 13:00:47.364628: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Internal: Failed to launch CUDA kernel: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  [...]
  File "file.py", line 293, in function
    print(f"Loss reduction: {self.function.loss(self.weights)-self.function.loss(self.weights+1*update)}")
  File "function.py", line 68, in loss
    p = self.predict(weights, self.X)
  File "function.py", line 88, in predict
    return logistic(data@weights + bias)
  File "function.py", line 52, in logistic
    return 1 / (1 + np.exp(-r))
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 404, in <lambda>
    fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 185, in exp
    return exp_p.bind(x)
  File "/home/user/.local/lib/python3.7/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/user/.local/lib/python3.7/site-packages/jax/core.py", line 606, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/user/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 232, in apply_primitive
    return compiled_fun(*args)
  File "/home/user/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 350, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-06-08 13:00:47.664840: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1039] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
	
[many empty lines]
	
	PyDict_SetItem
	_PyModule_ClearDict
	PyImport_Cleanup
	Py_FinalizeEx
	
	_Py_UnixMain
	__libc_start_main
	
*** End stack trace ***

2021-06-08 13:00:47.664934: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:89] Check failed: pair.first->SynchronizeAllActivity() 
```

np.linalg.eigh(a):
```
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/numpy/linalg.py", line 283, in eigh
    v, w = lax_linalg.eigh(a, lower=lower, symmetrize_input=symmetrize_input)
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/lax/linalg.py", line 111, in eigh
    x = symmetrize(x)
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/lax/linalg.py", line 299, in symmetrize
    def symmetrize(x): return (x + _H(x)) / 2
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 5666, in deferring_binary_op
    return binary_op(self, other)
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 427, in fn
    return lax_fn(x1, x2) if x1.dtype != bool_ else bool_lax_fn(x1, x2)
  File "/home/user/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 340, in add
    return add_p.bind(x, y)
  File "/home/user/.local/lib/python3.7/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/user/.local/lib/python3.7/site-packages/jax/core.py", line 606, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/user/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 232, in apply_primitive
    return compiled_fun(*args)
  File "/home/user/.local/lib/python3.7/site-packages/jax/interpreters/xla.py", line 350, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-06-08 13:17:31.165223: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1039] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
	
	PyDict_SetItem
	_PyModule_ClearDict
	PyImport_Cleanup
	Py_FinalizeEx
	
	_Py_UnixMain
	__libc_start_main
	
*** End stack trace ***

2021-06-08 13:17:31.165317: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:89] Check failed: pair.first->SynchronizeAllActivity() 
```

**Comment by hawkinsp** [comment]
We'd need a reproduction of the problem to make progress here.

**Comment by skye** [comment]
Like Peter says, we'll need code we can run ourselves to repro this problem. Can you share the code you're using to trigger this? Smaller repros are better, but a complicated repro is better than nothing.

Also, do you experience this issue with previous jaxlib versions?

**Comment by kuzlovsky** [comment]
Hello Skye,

I get a similar error when running this code: [nf-tutorial-jax](https://github.com/ericjang/nf-jax/blob/master/nf-tutorial-jax.ipynb)

If I make the model tiny by changing the code to "Dense(16), Relu, Dense(16)" then the error disappears.

Attaching the package versions I am using in requirements.txt, CUDA Version 10.1.243

Converting the notebook to python and running it gives an error as well.

For completeness the error I am getting is:
/tmp/ipykernel_16068/3820967770.py in <module>
     18 opt_state = opt_init(ps)
     19 for i in range(iters):
---> 20   opt_state = step(i, opt_state, next(data_generator))
     21 ps = get_params(opt_state)
     22 

ValueError: Internal: Failed to launch CUDA kernel: **CUDA_ERROR_ILLEGAL_ADDRESS**: an illegal memory access was encountered

[requirements.txt](https://github.com/google/jax/files/7077907/requirements.txt)

Regards,
Joe

**Comment by tomhennigan** [comment]
Perhaps google/jax#7752 is related?

**Comment by kuzlovsky** [comment]
I run the code for #7752 and it worked fine:
```
In[2]:import jax
  ...: import jax.numpy as jnp
  ...: 
  ...: a = jnp.ones([100, 100])
  ...: b = jnp.ones([100, 1])
  ...: c = jax.lax.dot_general(a, b, dimension_numbers=(((0,), (0,)), ((), ())))
  ...: c.block_until_ready()
Out[2]: 
DeviceArray([[100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.],
             [100.]], dtype=float32)

```

**Comment by kuzlovsky** [comment]
@hawkinsp were you able to reproduce the issue with [nf-tutorial-jax](https://github.com/ericjang/nf-jax/blob/master/nf-tutorial-jax.ipynb)?

**Comment by hawkinsp** [comment]
I believe the issue you are seeing in `nf-tutorial-jax` is a CUDA 11.0 bug (in `ptxas`). My best suggestion for now is "use a newer CUDA installation, although obviously that's difficult to do on Colab. Most likely there's not much we can do on the JAX side since it isn't our code that is buggy. I verified that CUDA 11.2 works. Hopefully Colab upgrades sometime soon.

**Comment by kuzlovsky** [comment]
Hello,

Thank you @hawkinsp, actually I was using CUDA Version 10.1.243 after installing cuda_11.4.1_470.57.02_linux.run I can confirm that the error went away.

Might be adding a note to the docs that CUDA 10 is buggy or dropping it's support.

You can close this ticket, @Baschdl can reopen if latest CUDA does not work for him.

Regards,
Joe

**Comment by Baschdl** [comment]
I have to get access to the machine where it happened again to test it and to check the CUDA version. Feel free to close it for now.

**Comment by hawkinsp** [comment]
Thanks. Our current belief is that CUDA 11.1 is the lowest version free of this bug.
