### ISSUE TITLE
Running gpu computation and cpu computation asynchronously?

### ISSUE THREAD

**Issue by epignatelli** [google/jax#7148]
I am trying to run two different functions in two different processes, the former computes on the cpu, and the latter computes on the gpu, but I am getting the error below.

I also tried using different initialisation context (`forkserver` and `fork`), but I still get errors.

Is there any way this pattern could work in jax?

```python
import functools
import multiprocessing as mp

import numpy as onp

import jax
import jax.numpy as jnp


@functools.partial(jax.jit, backend="cpu")
def cpu_ones(shape):
    return onp.ones((10,))


@functools.partial(jax.jit, backend="gpu")
def gpu_mean(x):
    return jnp.mean(x)


def producer(q, p):
    while True:
        print("Producing", q.qsize())
        x = jnp.ones((4, 16))
        for _ in range(30):
            x = cpu_ones((10,)) * p
            q.put(x)
    return


def consumer(q, p):
    while True:
        print("Consuming", q.qsize())
        x = q.get()
        params = gpu_mean(x) + 1
    return


def run_async():
    params = jnp.ones((10,))
    context = mp.get_context("spawn")

    m = context.Manager()
    queue = m.Queue(100)
    p = context.Process(target=producer, args=(queue, params), daemon=True)
    c = context.Process(target=consumer, args=(queue, params), daemon=True)

    try:
        print("Starting")
        p.start()
        c.start()
    except Exception as e:
        print("Failed", repr(e))
    finally:
        p.join()
        c.join()
    return


if __name__ == "__main__":
    run_async()

# outputs:
# 2021-06-30 14:01:12.601043: W external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 8511881216
# 2021-06-30 14:01:12.601412: F external/org_tensorflow/tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error Invalid argument: device CUDA:0 not supported by XLA service

```

- [ ] If applicable, include full error messages/tracebacks.

**Comment by epignatelli** [comment]
Some more info, this is the output with `TF_CPP_MIN_LOG_LEVEL=0`:

```
2021-06-30 14:30:49.726061: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x5596689fe3a0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:49.726090: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Interpreter, <undefined>
2021-06-30 14:30:49.747405: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x5596686b8c80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:49.747454: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2021-06-30 14:30:49.946652: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 14:30:49.954051: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 14:30:49.955341: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x559668c850a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:49.955372: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): GeForce GTX 1070 Ti, Compute Capability 6.1
2021-06-30 14:30:49.955383: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (1): GeForce GTX 1070 Ti, Compute Capability 6.1
2021-06-30 14:30:49.956146: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:298] Using BFC allocator.
2021-06-30 14:30:49.956213: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:257] XLA backend allocating 7537714790 bytes on device 0 for BFCAllocator.
2021-06-30 14:30:49.956276: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:257] XLA backend allocating 7563313152 bytes on device 1 for BFCAllocator.
2021-06-30 14:30:49.957376: I external/org_tensorflow/tensorflow/stream_executor/tpu/tpu_platform_interface.cc:74] No TPU platform found.
Starting
Producing 0
2021-06-30 14:30:51.198838: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x557127222ff0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.198861: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Interpreter, <undefined>
Consuming 0
2021-06-30 14:30:51.218790: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x557126c914c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.218814: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2021-06-30 14:30:51.321213: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 14:30:51.327364: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 14:30:51.327812: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x5571275abc40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.327857: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): GeForce GTX 1070 Ti, Compute Capability 6.1
2021-06-30 14:30:51.327870: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (1): GeForce GTX 1070 Ti, Compute Capability 6.1
2021-06-30 14:30:51.328804: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:298] Using BFC allocator.
2021-06-30 14:30:51.328878: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:257] XLA backend allocating 657063936 bytes on device 0 for BFCAllocator.
2021-06-30 14:30:51.328927: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:257] XLA backend allocating 7467997593 bytes on device 1 for BFCAllocator.
2021-06-30 14:30:51.329755: I external/org_tensorflow/tensorflow/stream_executor/tpu/tpu_platform_interface.cc:74] No TPU platform found.
2021-06-30 14:30:51.362643: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x55f88ac13ff0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.362671: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Interpreter, <undefined>
2021-06-30 14:30:51.365337: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x55f88a6824c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.365365: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
Producing 29
Producing 59
Producing 89
2021-06-30 14:30:51.481593: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 14:30:51.504927: W external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 8511881216
2021-06-30 14:30:51.505292: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:169] XLA service 0x55f88af9cc80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-30 14:30:51.505339: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): GeForce GTX 1070 Ti, Compute Capability 6.1
2021-06-30 14:30:51.505369: F external/org_tensorflow/tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error Invalid argument: device CUDA:0 not supported by XLA service
```

**Comment by epignatelli** [comment]
Actually, I noticed that adding `print(jax.process_index()` in both `producer` and `consumer` removes the error.
But `jax.process_index()` is calling `get_backend(backend)`, which is in turn wrapping the call in a `threading.Lock()`.

The code is now running, but are the two calls, the one to the cpu and the one to the gpu, running asynchronously?

**Comment by skye** [comment]
Running your original script works for me without error, I think because I only have a single GPU. It looks like you have two GPUs, and that's somehow causing an issue. This looks like a bug to me, so thanks for reporting! JAX will always try to initialize all backends, even when only one is requested. However, the GPU backend failing to initialize in the producer process ideally shouldn't cause a problem, as it should fall back to CPU. 

Can you share the Python stack trace, if any, you get when the original script fails?

**Comment by epignatelli** [comment]
Thanks @skye ! This is the stack trace of the comsumer process, which seems likely meager:
```
  File "<string>", line 1, in <module>
  File "/home/epignatelli/miniconda3/envs/helx/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/epignatelli/miniconda3/envs/helx/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/epignatelli/miniconda3/envs/helx/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/epignatelli/miniconda3/envs/helx/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/epignatelli/repos/helx/test/test_impala.py", line 107, in consumer
    traceback.print_stack()
```

Is there a better way to catch the call stack in python?

**Comment by epignatelli** [comment]
I add a bit more logging to the `xla_client._get_local_backends()` function to understand what is happening, I hope this is useful:

<summary>
<details>


![image](https://user-images.githubusercontent.com/26899347/124147889-07b9f680-da87-11eb-9b8f-b5f3d73b3378.png)


</details>
</summary>

**Comment by epignatelli** [comment]
Sorry for the monologue - I tested the hypothesis and if the backends are initialised eagerly, the issue disappears.
https://github.com/epignatelli/jax/commit/6d4d67aa73e81dd923f0502a6c168dfe193abc4d

However, that seems quite low level, and I don't feel too confident in understanding its side effects.
Hopefully that can shed some light, though!

**Comment by epignatelli** [comment]
While this moves forwards, the workaround I found is to explicitly call `xla_bridge.backends()` at the initialisation of any process. This should initialise all backends as soon as the process starts, i.e.:
```python
from jax.lib import xla_bridge as xb


def producer(q, p, i):
   xb.backends()
    while True:
        print(
            "[{}]".format(time.time()),
            "Producing",
            "Process {}".format(i),
            "Size {}".format(q.qsize()),
        )
        x = cpu_ones((10,)) * p
        q.put(x)
        time.sleep(0.5)
    return
```
