### ISSUE TITLE
take_along_axis needs much TPU memory

### ISSUE THREAD

**Issue by juliuskunze** [google/jax#7502]
Running

```python
from jax import numpy as jnp, jit

@jit
def t(x):
    indices = jnp.zeros_like(x, jnp.int32)
    return jnp.take_along_axis(x, indices, 1)

t(jnp.zeros((2048, 1, 128, 128)))
```

on TPU results in 

```
RuntimeError: Resource exhausted: Ran out of memory in memory space hbm. Used 64.00G of 15.48G hbm. Exceeded hbm capacity by 48.52G.

Total hbm usage >= 64.52G:
    reserved        530.00M
    program          64.00G
    arguments            0B

Output size 0B; shares 0B with arguments.

Program hbm requirement 64.00G:
    global             4.0K
    HLO temp         64.00G (1.4% utilization: Unpadded (896.00M) Padded (64.00G), 0.0% fragmentation (0B))

  Largest program allocations in hbm:

  1. Size: 16.00G
     Operator: op_type="concatenate" op_name="jit(t)/jit(_take_along_axis)/concatenate[ dimension=4 ]" source_file="t.py" source_line=6
     Shape: s32[2048,1,128,128,4]{4,3,2,0,1:T(8,128)}
     Unpadded size: 512.00M
     Extra memory due to padding: 15.50G (32.0x expansion)
     XLA label: %fusion.1 = s32[2048,1,128,128,4]{4,3,2,0,1:T(8,128)} fusion(s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)} %iota.5.clone2.remat_uncompressed, s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)} %iota.4.clone2.remat_uncompressed, s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)}...
     Allocation type: HLO temp
     ==========================

  2. Size: 16.00G
     Shape: s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)}
     Unpadded size: 128.00M
     Extra memory due to padding: 15.88G (128.0x expansion)
     XLA label: %iota.3.clone2.remat_uncompressed = s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)} copy(s32[2048,1,128,128,1]{3,2,4,1,0:T(8,128)} %iota.3.clone2.remat_compressed)
     Allocation type: HLO temp
     ==========================

  3. Size: 16.00G
     Shape: s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)}
     Unpadded size: 128.00M
     Extra memory due to padding: 15.88G (128.0x expansion)
     XLA label: %iota.4.clone2.remat_uncompressed = s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)} copy(s32[2048,1,128,128,1]{3,2,4,1,0:T(8,128)} %iota.4.clone2.remat_compressed)
     Allocation type: HLO temp
     ==========================

  4. Size: 16.00G
     Shape: s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)}
     Unpadded size: 128.00M
     Extra memory due to padding: 15.88G (128.0x expansion)
     XLA label: %iota.5.clone2.remat_uncompressed = s32[2048,1,128,128,1]{4,3,2,0,1:T(8,128)} copy(s32[2048,1,128,128,1]{3,2,4,1,0:T(8,128)} %iota.5.clone2.remat_compressed)
     Allocation type: HLO temp

[...]
```

Notice how the unpadded size is <1GB, but padding suddenly requires 64GB. The [TPU performance guide](https://cloud.google.com/tpu/docs/performance-guide) encourages having two different dimensions with sizes being multiples of 8 and 128 respectively since TPU stores data in blocks of 8 x 128 and XLA sometimes pads to that size.

Why is memory blowup due to padding so severe in this seemingly simple, TPU-friendly example?

**Comment by rajasekharporeddy** [comment]
Hi @juliuskunze 

Looks like this issue is resolved in the JAX version 0.3.25 on TPU.

I ran your code on Google Colab where it takes around 1GB memory when run on TPU.

Please find the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/1ae1755d2c4de6f49f00c3eef115b3c4/-7502.ipynb) here.

Thank you.
