### ISSUE TITLE
RTX 3080 Convolution Error

### ISSUE THREAD

**Issue by dimy93** [google/jax#7953]
With the follwoing conda environment installed via:

`conda env create --name fed_jax --file=environment.yml` 

with environment.yml :
```
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.5.30=ha878542_0
  - cudatoolkit=11.2.2=he111cf0_8
  - cudatoolkit-dev=11.4.0=py39h3811e60_1
  - cudnn=8.2.1.32=h86fa8c9_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h9c3ff4c_1
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgomp=11.2.0=h1d223b6_8
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - ncurses=6.2=h58526e2_4
  - openssl=1.1.1l=h7f98852_0
  - pip=21.2.4=pyhd8ed1ab_0
  - python=3.9.7=hb7a2778_1_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1=h46c0cb4_0
  - setuptools=58.0.4=py39hf3d152e_0
  - sqlite=3.36.0=h9cd32fc_1
  - tk=8.6.11=h27826a3_1
  - tzdata=2021a=he74cb21_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - absl-py==0.13.0
    - chex==0.0.8
    - cloudpickle==2.0.0
    - cycler==0.10.0
    - decorator==5.1.0
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - flax==0.3.4
    - gast==0.5.2
    - jax==0.2.20
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - msgpack==1.0.2
    - numpy==1.21.2
    - opt-einsum==3.3.0
    - optax==0.0.9
    - pillow==8.3.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - six==1.16.0
    - tensorflow-probability==0.14.0
    - threadpoolctl==2.2.0
    - toolz==0.11.1
    - torch==1.9.0
    - torchvision==0.10.0
    - tqdm==4.62.2
    - typing-extensions==3.10.0.2
```

Alongside jax with GPU support installed via:

`pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html`

inside the environment on a machines with NVIDIA driver 460.91.03 the following code work on GeForce RTX 2080 Ti but doesn't on GeForce RTX 3080:
```
from jax import numpy as jnp, random, lax

key = random.PRNGKey(1701)

kernel = jnp.zeros((3, 3, 3, 3))
kernel += jnp.array([[1, 1, 0],
                     [1, 0,-1],
                     [0,-1,1]])[:, :, jnp.newaxis, jnp.newaxis]

img = jnp.zeros((1, 200, 198, 3))

for k in range(3):
    x = 30 + 60 * k
    y = 20 + 60 * k
    img = img.at[0, x:x+10, y:y+10, k].set(1)

out = lax.conv(jnp.transpose(img, [0,3,1,2]),
               jnp.transpose(kernel, [3,2,0,1]),
               (1, 1),
               'SAME')
```
On the 3080 the following error occurs:
```
2021-09-17 21:24:19.912296: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:711] Failed to determine best cudnn convolution algorithm: INTERNAL: All algorithms tried for %custom-call = (f32[1,3,200,198]{3,2,1,0}, u8[0]{0}) custom-call(f32[1,3,200,198]{3,2,1,0} %parameter.1, f32[3,3,3,3]{3,2,1,0} %parameter.2), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="conv_general_dilated" op_name="conv_general_dilated[ batch_group_count=1\n                      dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2, 3), rhs_spec=(0, 1, 2, 3), out_spec=(0, 1, 2, 3))\n                      feature_group_count=1\n                      lhs_dilation=(1, 1)\n                      lhs_shape=(1, 3, 200, 198)\n                      padding=((1, 1), (1, 1))\n                      precision=None\n                      preferred_element_type=None\n                      rhs_dilation=(1, 1)\n                      rhs_shape=(3, 3, 3, 3)\n                      window_strides=(1, 1) ]"}, backend_config="{\"algorithm\":\"0\",\"tensor_ops_enabled\":false,\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm. 

Convolution performance may be suboptimal.
2021-09-17 21:24:19.915951: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2085] Execution of replica 0 failed: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4004): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd.handle(), input_data.opaque(), filter_nd.handle(), filter_data.opaque(), conv.handle(), ToConvForwardAlgo(algorithm_desc), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd.handle(), output_data.opaque())'
Traceback (most recent call last):
  File "/home/dimitadi/hdd1/federated_mislav/federated-grad/sth.py", line 20, in <module>
    out = lax.conv(jnp.transpose(img, [0,3,1,2]),
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 1723, in conv
    return conv_general_dilated(lhs, rhs, window_strides, padding,
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 629, in conv_general_dilated
    return conv_general_dilated_p.bind(
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/core.py", line 267, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/core.py", line 612, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/interpreters/xla.py", line 275, in apply_primitive
    return compiled_fun(*args)
  File "/home/dimitadi/miniconda3/envs/fed_jax/lib/python3.9/site-packages/jax/interpreters/xla.py", line 391, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4004): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd.handle(), input_data.opaque(), filter_nd.handle(), filter_data.opaque(), conv.handle(), ToConvForwardAlgo(algorithm_desc), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd.handle(), output_data.opaque())'
```
I know similar issues have been reported before but given that the exact same environment works on one GPU and doesn't on the other and the fact that pytorch had to implemented updates to support 30xx graphic cards series I assume it is 3080 specific problem. Can you take a look?

**Comment by pseudo-rnd-thoughts** [comment]
Im getting the same error message, did you have an success fixing the bug?

**Comment by zhangqiaorjc** [comment]
See https://github.com/google/jax/issues/8506#issuecomment-971916446

Possibly 3080 specific bug

**Comment by zhangqiaorjc** [comment]
This is likely already fixed in the latest jaxlib 0.1.74. Could you upgrade jaxlib and try again?

**Comment by dimy93** [comment]
I can confirm Jax is now working on my 3080

**Comment by hawkinsp** [comment]
That's awesome! Happy to hear that.
