### ISSUE TITLE
pmap forces huge memory allocation that scales linearly w/ batch size, invariant to device count

### ISSUE THREAD

**Issue by awehrs** [google/jax#9035]
I'm debugging a small model with a small dataset (~2gb). However, whether I run this locally, or on a couple of TPUs, pmap-ing my train_step function creates an enormous memory allocation, which scales linearly with batch-size. For instance, when I set the batch size to 16, the memory allocation is ~16gb; at a batch size of 32, memory blows out to ~32gb (see stack traces, below). Perplexingly, when I run the same code locally, but jit my train_step function instead of pmap it, I don't encounter the same memory allocation issues. 

Here is my main training loop: 

```python
def train_and_evaluate(config: ml_collections.ConfigDict, workdir: str) -> TrainState:
    """Execute model training and evaluation loop.

    Args:
        config: Hyperparameter configuration for training and evaluation.
        workdir: Directory where the tensorboard summaries are written to.

    Returns:
        Final TrainState.
    """

    writer = metric_writers.create_default_writer(
        logdir=workdir, just_logging=jax.process_index() != 0
    )

    rng = random.PRNGKey(0)

    image_size = 224

    if config.batch_size % jax.device_count() > 0:
        raise ValueError("Batch size must be divisible by the number of devices")
    local_batch_size = config.batch_size // jax.process_count()

    platform = jax.local_devices()[0].platform

    if config.half_precision:
        if platform == "tpu":
            input_dtype = tf.bfloat16
        else:
            input_dtype = tf.float16
    else:
        input_dtype = tf.float32

    dataset_builder = tfds.builder(config.dataset)

    train_iter = create_input_iter(
        dataset_builder,
        local_batch_size,
        image_size,
        input_dtype,
        train=True,
        cache=config.cache,
    )

    eval_iter = create_input_iter(
        dataset_builder,
        local_batch_size,
        image_size,
        input_dtype,
        train=False,
        cache=config.cache,
    )

    steps_per_epoch = (
        dataset_builder.info.splits["train"].num_examples // config.batch_size
    )

    if config.num_train_steps == -1:
        num_steps = int(steps_per_epoch * config.num_epochs)
    else:
        num_steps = config.num_train_steps

    if config.steps_per_eval == -1:
        num_validation_examples = dataset_builder.info.splits["validation"].num_examples
        steps_per_eval = num_validation_examples // config.batch_size
    else:
        steps_per_eval = config.steps_per_eval

    steps_per_checkpoint = steps_per_epoch * 10

    base_learning_rate = config.learning_rate * config.batch_size / 256.0

    model = create_model(half_precision=config.half_precision, config=config)

    learning_rate_fn = create_learning_rate_fn(
        config, base_learning_rate, steps_per_epoch
    )

    state = create_train_state(rng, config, model, image_size, learning_rate_fn)

    state = restore_checkpoint(state, workdir)

    # step_offset > 0 if restarting from checkpoint
    step_offset = int(state.step)
    state = jax_utils.replicate(state)
    p_train_step = jax.pmap(
        functools.partial(train_step, learning_rate_fn=learning_rate_fn),
        axis_name="batch",
    )
    p_eval_step = jax.pmap(eval_step, axis_name="batch")

    train_metrics = []
    hooks = []
    if jax.process_index() == 0:
        hooks += [periodic_actions.Profile(num_profile_steps=5, logdir=workdir)]
    train_metrics_last_t = time.time()
    logging.info("Initial compilation, this might take some minutes...")
    for step, batch in zip(range(step_offset, num_steps), train_iter):
        state, metrics = p_train_step(state, batch)
        # doesn't return from this call 
        # [ ... ]
```

And here is my train step, which, as you can see above, gets pmap-ed. 
 
```python
def train_step(state, batch, learning_rate_fn):
    """Perform a single training step."""
    print(batch["image"].shape)

    def loss_fn(params):
        """loss function used for training."""
        logits, new_model_state = state.apply_fn(
            {"params": params, "batch_stats": state.batch_stats},
            batch["image"],
            mutable=["batch_stats"],
            is_training=True,
        )
        loss = cross_entropy_loss(logits, batch["label"])
        weight_penalty_params = jax.tree_leaves(params)
        weight_decay = 0.0001
        weight_l2 = sum([jnp.sum(x ** 2) for x in weight_penalty_params if x.ndim > 1])
        weight_penalty = weight_decay * 0.5 * weight_l2
        loss = loss + weight_penalty
        return loss, (new_model_state, logits)

    step = state.step
    dynamic_scale = state.dynamic_scale
    lr = learning_rate_fn(step)

    if dynamic_scale:
        grad_fn = dynamic_scale.value_and_grad(loss_fn, has_aux=True, axis_name="batch")
        dynamic_scale, is_fin, aux, grads = grad_fn(state.params)
        # dynamic loss takes care of averaging gradients across replicas
    else:
        grad_fn = jax.value_and_grad(loss_fn, has_aux=True)
        aux, grads = grad_fn(state.params)
        # Re-use same axis_name as in the call to `pmap(...train_step...)` below.
        grads = lax.pmean(grads, axis_name="batch")
    new_model_state, logits = aux[1]
    metrics = compute_metrics(logits, batch["label"])
    metrics["learning_rate"] = lr
    new_state = state.apply_gradients(
        grads=grads, batch_stats=new_model_state["batch_stats"]
    )
    if dynamic_scale:
        # if is_fin == False the gradients contain Inf/NaNs and optimizer state and
        # params should be restored (= skip this step).
        new_state = new_state.replace(
            opt_state=jax.tree_multimap(
                functools.partial(jnp.where, is_fin),
                new_state.opt_state,
                state.opt_state,
            ),
            params=jax.tree_multimap(
                functools.partial(jnp.where, is_fin), new_state.params, state.params
            ),
        )
        metrics["scale"] = dynamic_scale.scale
        # this line gets reached, but apparently the return never goes through
    return new_state, metrics
```
And, for good measure, here is how the model is initialized

```python
def initialized(key, image_size, model):
    input_shape = (1, image_size, image_size, 3)

    @jax.jit
    def init(*args):
        return model.init(*args, is_training=False)

    variables = init(key, jnp.ones(input_shape)) 
    [ ... ]
```
Here is the stack trace with batch size set to 16:

```
File ".../train.py", line 402, in train_and_evaluate
    epoch = step // steps_per_epoch
  File ".../lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1502, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 15759928848 bytes.
```
And with a with a batch size of 32: 

```
 .../train.py", line 380, in train_and_evaluate
    state, metrics = p_train_step(state, batch)
 .../lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1502, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 31538931728 bytes
31538931728 bytes.
```
And a stack trace when running on 8 TPUs (this happens much earlier in the compilation process). 

```
RuntimeError: RESOURCE_EXHAUSTED: Ran out of memory in memory space hbm. Used 9.47G of 7.48G hbm. Exceeded hbm capacity by 1.98G.
```

Any insight into what could be going on here would be much appreciated.

**Comment by mattjj** [comment]
Thanks for reporting the issue.

Hrm, this is surprising... any chance you could provide a runnable, minimal repro?

**Comment by versae** [comment]
Having the same issue when using Jax in the Tranformers library. @awehrs were you able to fix it?

**Comment by awehrs** [comment]
@versae, i rewrote everything in haiku (had been using flax) and it fixed it for some reason :/

**Comment by qlan3** [comment]
How large is your HBM utilization? Is it low?

**Comment by hawkinsp** [comment]
I'm going to close this, because we never got a runnable reproduction of the problem, and without that I can't even determine if the issue is fixed or not. If you're still having trouble and can provide a runnable reproduction, we'd be delighted to take a look.
